begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.dataformat.xmlsecurity
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|dataformat
operator|.
name|xmlsecurity
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|ByteArrayInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Document
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|NodeList
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Exchange
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Message
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Processor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|builder
operator|.
name|RouteBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|converter
operator|.
name|jaxp
operator|.
name|XmlConverter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|test
operator|.
name|junit4
operator|.
name|CamelTestSupport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|xml
operator|.
name|security
operator|.
name|encryption
operator|.
name|XMLCipher
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_comment
comment|/**  * Unit test of the encryptXML data format.  */
end_comment

begin_class
DECL|class|XMLSecurityDataFormatTest
specifier|public
class|class
name|XMLSecurityDataFormatTest
extends|extends
name|CamelTestSupport
block|{
DECL|field|XML_FRAGMENT
specifier|private
specifier|static
specifier|final
name|String
name|XML_FRAGMENT
init|=
literal|"<?xml version=\"1.0\" encoding=\"UTF-8\" ?>"
operator|+
literal|"<cheesesites>"
operator|+
literal|"<netherlands>"
operator|+
literal|"<source>cow</source>"
operator|+
literal|"<cheese>gouda</cheese>"
operator|+
literal|"</netherlands>"
operator|+
literal|"<italy>"
operator|+
literal|"<source>cow</source>"
operator|+
literal|"<cheese>gorgonzola</cheese>"
operator|+
literal|"</italy>"
operator|+
literal|"<france>"
operator|+
literal|"<source>goat</source>"
operator|+
literal|"<cheese>brie</cheese>"
operator|+
literal|"</france>"
operator|+
literal|"</cheesesites>"
decl_stmt|;
annotation|@
name|Override
DECL|method|isUseRouteBuilder ()
specifier|public
name|boolean
name|isUseRouteBuilder
parameter_list|()
block|{
return|return
literal|false
return|;
block|}
DECL|method|sendText ()
specifier|private
name|void
name|sendText
parameter_list|()
throws|throws
name|Exception
block|{
name|template
operator|.
name|send
argument_list|(
literal|"direct:start"
argument_list|,
operator|new
name|Processor
argument_list|()
block|{
specifier|public
name|void
name|process
parameter_list|(
name|Exchange
name|exchange
parameter_list|)
throws|throws
name|Exception
block|{
comment|// Set the property of the charset encoding
name|exchange
operator|.
name|setProperty
argument_list|(
name|Exchange
operator|.
name|CHARSET_NAME
argument_list|,
literal|"UTF-8"
argument_list|)
expr_stmt|;
name|Message
name|in
init|=
name|exchange
operator|.
name|getIn
argument_list|()
decl_stmt|;
name|in
operator|.
name|setBody
argument_list|(
name|XML_FRAGMENT
argument_list|)
expr_stmt|;
name|log
operator|.
name|info
argument_list|(
literal|"xmlFragment: "
operator|+
name|XML_FRAGMENT
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
block|}
comment|/*      * Encryption Tests      */
annotation|@
name|Test
DECL|method|testFullPayloadXMLEncryption ()
specifier|public
name|void
name|testFullPayloadXMLEncryption
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|()
operator|.
name|process
argument_list|(
operator|new
name|EncryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadXMLContentEncryption ()
specifier|public
name|void
name|testPartialPayloadXMLContentEncryption
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/italy/cheese"
argument_list|,
literal|true
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|EncryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadMultiNodeXMLContentEncryption ()
specifier|public
name|void
name|testPartialPayloadMultiNodeXMLContentEncryption
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/*/cheese"
argument_list|,
literal|true
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|EncryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadXMLElementEncryptionWithKey ()
specifier|public
name|void
name|testPartialPayloadXMLElementEncryptionWithKey
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/france/cheese"
argument_list|,
literal|false
argument_list|,
literal|"Just another 24 Byte key"
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|EncryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadXMLElementEncryptionWithKeyAndAlgorithm ()
specifier|public
name|void
name|testPartialPayloadXMLElementEncryptionWithKeyAndAlgorithm
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|byte
index|[]
name|bits128
init|=
block|{
operator|(
name|byte
operator|)
literal|0x08
block|,
operator|(
name|byte
operator|)
literal|0x09
block|,
operator|(
name|byte
operator|)
literal|0x0A
block|,
operator|(
name|byte
operator|)
literal|0x0B
block|,
operator|(
name|byte
operator|)
literal|0x0C
block|,
operator|(
name|byte
operator|)
literal|0x0D
block|,
operator|(
name|byte
operator|)
literal|0x0E
block|,
operator|(
name|byte
operator|)
literal|0x0F
block|,
operator|(
name|byte
operator|)
literal|0x10
block|,
operator|(
name|byte
operator|)
literal|0x11
block|,
operator|(
name|byte
operator|)
literal|0x12
block|,
operator|(
name|byte
operator|)
literal|0x13
block|,
operator|(
name|byte
operator|)
literal|0x14
block|,
operator|(
name|byte
operator|)
literal|0x15
block|,
operator|(
name|byte
operator|)
literal|0x16
block|,
operator|(
name|byte
operator|)
literal|0x17
block|}
decl_stmt|;
specifier|final
name|String
name|passCode
init|=
operator|new
name|String
argument_list|(
name|bits128
argument_list|)
decl_stmt|;
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/netherlands"
argument_list|,
literal|false
argument_list|,
name|passCode
argument_list|,
name|XMLCipher
operator|.
name|AES_128
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|EncryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
comment|/*     * Decryption Tests     */
annotation|@
name|Test
DECL|method|testFullPayloadXMLDecryption ()
specifier|public
name|void
name|testFullPayloadXMLDecryption
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|()
operator|.
name|unmarshal
argument_list|()
operator|.
name|secureXML
argument_list|()
operator|.
name|process
argument_list|(
operator|new
name|DecryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadXMLContentDecryption ()
specifier|public
name|void
name|testPartialPayloadXMLContentDecryption
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/italy/cheese"
argument_list|,
literal|true
argument_list|)
operator|.
name|unmarshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/italy/cheese"
argument_list|,
literal|true
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|DecryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadMultiNodeXMLContentDecryption ()
specifier|public
name|void
name|testPartialPayloadMultiNodeXMLContentDecryption
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/*/cheese"
argument_list|,
literal|true
argument_list|)
operator|.
name|unmarshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/*/cheese"
argument_list|,
literal|true
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|DecryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadXMLElementDecryptionWithKey ()
specifier|public
name|void
name|testPartialPayloadXMLElementDecryptionWithKey
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/france/cheese"
argument_list|,
literal|false
argument_list|,
literal|"Just another 24 Byte key"
argument_list|)
operator|.
name|unmarshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"//cheesesites/france"
argument_list|,
literal|false
argument_list|,
literal|"Just another 24 Byte key"
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|DecryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testPartialPayloadXMLContentDecryptionWithKeyAndAlgorithm ()
specifier|public
name|void
name|testPartialPayloadXMLContentDecryptionWithKeyAndAlgorithm
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|byte
index|[]
name|bits128
init|=
block|{
operator|(
name|byte
operator|)
literal|0x08
block|,
operator|(
name|byte
operator|)
literal|0x09
block|,
operator|(
name|byte
operator|)
literal|0x0A
block|,
operator|(
name|byte
operator|)
literal|0x0B
block|,
operator|(
name|byte
operator|)
literal|0x0C
block|,
operator|(
name|byte
operator|)
literal|0x0D
block|,
operator|(
name|byte
operator|)
literal|0x0E
block|,
operator|(
name|byte
operator|)
literal|0x0F
block|,
operator|(
name|byte
operator|)
literal|0x10
block|,
operator|(
name|byte
operator|)
literal|0x11
block|,
operator|(
name|byte
operator|)
literal|0x12
block|,
operator|(
name|byte
operator|)
literal|0x13
block|,
operator|(
name|byte
operator|)
literal|0x14
block|,
operator|(
name|byte
operator|)
literal|0x15
block|,
operator|(
name|byte
operator|)
literal|0x16
block|,
operator|(
name|byte
operator|)
literal|0x17
block|}
decl_stmt|;
specifier|final
name|String
name|passCode
init|=
operator|new
name|String
argument_list|(
name|bits128
argument_list|)
decl_stmt|;
name|context
operator|.
name|addRoutes
argument_list|(
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|marshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"cheese"
argument_list|,
literal|true
argument_list|,
name|passCode
argument_list|,
name|XMLCipher
operator|.
name|AES_128
argument_list|)
operator|.
name|unmarshal
argument_list|()
operator|.
name|secureXML
argument_list|(
literal|"cheese"
argument_list|,
literal|true
argument_list|,
name|passCode
argument_list|,
name|XMLCipher
operator|.
name|AES_128
argument_list|)
operator|.
name|process
argument_list|(
operator|new
name|DecryptedXMLMessageProcessor
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|sendText
argument_list|()
expr_stmt|;
block|}
DECL|class|EncryptedXMLMessageProcessor
specifier|private
class|class
name|EncryptedXMLMessageProcessor
implements|implements
name|Processor
block|{
DECL|method|process (Exchange exchange)
specifier|public
name|void
name|process
parameter_list|(
name|Exchange
name|exchange
parameter_list|)
throws|throws
name|Exception
block|{
name|byte
index|[]
name|body
init|=
name|exchange
operator|.
name|getIn
argument_list|()
operator|.
name|getBody
argument_list|(
name|byte
index|[]
operator|.
expr|class
argument_list|)
decl_stmt|;
name|Document
name|d
init|=
name|createDocumentfromInputStream
argument_list|(
operator|new
name|ByteArrayInputStream
argument_list|(
name|body
argument_list|)
argument_list|)
decl_stmt|;
name|NodeList
name|nodeList
init|=
name|d
operator|.
name|getElementsByTagNameNS
argument_list|(
literal|"http://www.w3.org/2001/04/xmlenc#"
argument_list|,
literal|"EncryptedData"
argument_list|)
decl_stmt|;
if|if
condition|(
name|nodeList
operator|.
name|getLength
argument_list|()
operator|>=
literal|0
condition|)
block|{
name|assertTrue
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|assertTrue
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
block|}
block|}
DECL|class|DecryptedXMLMessageProcessor
specifier|private
class|class
name|DecryptedXMLMessageProcessor
implements|implements
name|Processor
block|{
DECL|method|process (Exchange exchange)
specifier|public
name|void
name|process
parameter_list|(
name|Exchange
name|exchange
parameter_list|)
throws|throws
name|Exception
block|{
name|byte
index|[]
name|body
init|=
name|exchange
operator|.
name|getIn
argument_list|()
operator|.
name|getBody
argument_list|(
name|byte
index|[]
operator|.
expr|class
argument_list|)
decl_stmt|;
name|Document
name|d
init|=
name|createDocumentfromInputStream
argument_list|(
operator|new
name|ByteArrayInputStream
argument_list|(
name|body
argument_list|)
argument_list|)
decl_stmt|;
name|NodeList
name|nodeList
init|=
name|d
operator|.
name|getElementsByTagNameNS
argument_list|(
literal|"http://www.w3.org/2001/04/xmlenc#"
argument_list|,
literal|"EncryptedData"
argument_list|)
decl_stmt|;
if|if
condition|(
name|nodeList
operator|.
name|getLength
argument_list|()
operator|==
literal|0
condition|)
block|{
name|assertTrue
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|assertTrue
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
block|}
block|}
DECL|method|createDocumentfromInputStream (InputStream is)
specifier|private
name|Document
name|createDocumentfromInputStream
parameter_list|(
name|InputStream
name|is
parameter_list|)
block|{
return|return
name|context
operator|.
name|getTypeConverter
argument_list|()
operator|.
name|convertTo
argument_list|(
name|Document
operator|.
name|class
argument_list|,
name|is
argument_list|)
return|;
block|}
block|}
end_class

end_unit

