begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.processor.idempotent.jdbc
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|processor
operator|.
name|idempotent
operator|.
name|jdbc
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|sql
operator|.
name|DataSource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|api
operator|.
name|management
operator|.
name|ManagedOperation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|api
operator|.
name|management
operator|.
name|ManagedResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|spi
operator|.
name|IdempotentRepository
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|support
operator|.
name|ServiceSupport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|jdbc
operator|.
name|core
operator|.
name|JdbcTemplate
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|jdbc
operator|.
name|datasource
operator|.
name|DataSourceTransactionManager
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|transaction
operator|.
name|TransactionDefinition
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|transaction
operator|.
name|TransactionStatus
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|transaction
operator|.
name|support
operator|.
name|TransactionCallback
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|transaction
operator|.
name|support
operator|.
name|TransactionTemplate
import|;
end_import

begin_comment
comment|/**  * Base class for JDBC-based idempotent repositories that allows the schema to be changed.  *<p/>  * Subclasses need only implement theses methods:  *<ul>  *<li>{@link #queryForInt(T key)}</li>  *<li>{@link #insert(T key)}</li>  *<li>{@link #delete(T key)}</li>  *</ul>  *<p/>  * These methods should perform the named database operation.  */
end_comment

begin_class
annotation|@
name|ManagedResource
argument_list|(
name|description
operator|=
literal|"JDBC IdempotentRepository"
argument_list|)
DECL|class|AbstractJdbcMessageIdRepository
specifier|public
specifier|abstract
class|class
name|AbstractJdbcMessageIdRepository
parameter_list|<
name|T
parameter_list|>
extends|extends
name|ServiceSupport
implements|implements
name|IdempotentRepository
argument_list|<
name|T
argument_list|>
block|{
DECL|field|jdbcTemplate
specifier|protected
name|JdbcTemplate
name|jdbcTemplate
decl_stmt|;
DECL|field|processorName
specifier|protected
name|String
name|processorName
decl_stmt|;
DECL|field|transactionTemplate
specifier|protected
name|TransactionTemplate
name|transactionTemplate
decl_stmt|;
DECL|field|dataSource
specifier|protected
name|DataSource
name|dataSource
decl_stmt|;
DECL|field|log
specifier|protected
specifier|transient
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|getClass
argument_list|()
argument_list|)
decl_stmt|;
DECL|method|AbstractJdbcMessageIdRepository ()
specifier|public
name|AbstractJdbcMessageIdRepository
parameter_list|()
block|{     }
DECL|method|AbstractJdbcMessageIdRepository (JdbcTemplate jdbcTemplate, TransactionTemplate transactionTemplate)
specifier|public
name|AbstractJdbcMessageIdRepository
parameter_list|(
name|JdbcTemplate
name|jdbcTemplate
parameter_list|,
name|TransactionTemplate
name|transactionTemplate
parameter_list|)
block|{
name|this
operator|.
name|jdbcTemplate
operator|=
name|jdbcTemplate
expr_stmt|;
name|this
operator|.
name|transactionTemplate
operator|=
name|transactionTemplate
expr_stmt|;
block|}
DECL|method|AbstractJdbcMessageIdRepository (DataSource dataSource, TransactionTemplate transactionTemplate, String processorName)
specifier|public
name|AbstractJdbcMessageIdRepository
parameter_list|(
name|DataSource
name|dataSource
parameter_list|,
name|TransactionTemplate
name|transactionTemplate
parameter_list|,
name|String
name|processorName
parameter_list|)
block|{
name|this
operator|.
name|jdbcTemplate
operator|=
operator|new
name|JdbcTemplate
argument_list|(
name|dataSource
argument_list|)
expr_stmt|;
name|this
operator|.
name|jdbcTemplate
operator|.
name|afterPropertiesSet
argument_list|()
expr_stmt|;
name|this
operator|.
name|processorName
operator|=
name|processorName
expr_stmt|;
name|this
operator|.
name|transactionTemplate
operator|=
name|transactionTemplate
expr_stmt|;
block|}
DECL|method|AbstractJdbcMessageIdRepository (DataSource dataSource, String processorName)
specifier|public
name|AbstractJdbcMessageIdRepository
parameter_list|(
name|DataSource
name|dataSource
parameter_list|,
name|String
name|processorName
parameter_list|)
block|{
name|this
argument_list|(
name|dataSource
argument_list|,
name|createTransactionTemplate
argument_list|(
name|dataSource
argument_list|)
argument_list|,
name|processorName
argument_list|)
expr_stmt|;
block|}
comment|/**      * Operation that returns the number of rows, if any, for the specified key      *      * @param key  the key      * @return int number of rows      */
DECL|method|queryForInt (final T key)
specifier|protected
specifier|abstract
name|int
name|queryForInt
parameter_list|(
specifier|final
name|T
name|key
parameter_list|)
function_decl|;
comment|/**      * Operation that inserts the key if it does not already exist      *      * @param key  the key      * @return int number of rows inserted      */
DECL|method|insert (final T key)
specifier|protected
specifier|abstract
name|int
name|insert
parameter_list|(
specifier|final
name|T
name|key
parameter_list|)
function_decl|;
comment|/**      * Operations that deletes the key if it exists      *      * @param key  the key      * @return int number of rows deleted      */
DECL|method|delete (final T key)
specifier|protected
specifier|abstract
name|int
name|delete
parameter_list|(
specifier|final
name|T
name|key
parameter_list|)
function_decl|;
comment|/**      * Creates the transaction template      */
DECL|method|createTransactionTemplate (DataSource dataSource)
specifier|protected
specifier|static
name|TransactionTemplate
name|createTransactionTemplate
parameter_list|(
name|DataSource
name|dataSource
parameter_list|)
block|{
name|TransactionTemplate
name|transactionTemplate
init|=
operator|new
name|TransactionTemplate
argument_list|()
decl_stmt|;
name|transactionTemplate
operator|.
name|setTransactionManager
argument_list|(
operator|new
name|DataSourceTransactionManager
argument_list|(
name|dataSource
argument_list|)
argument_list|)
expr_stmt|;
name|transactionTemplate
operator|.
name|setPropagationBehavior
argument_list|(
name|TransactionDefinition
operator|.
name|PROPAGATION_REQUIRED
argument_list|)
expr_stmt|;
return|return
name|transactionTemplate
return|;
block|}
annotation|@
name|Override
DECL|method|doStart ()
specifier|protected
name|void
name|doStart
parameter_list|()
throws|throws
name|Exception
block|{     }
annotation|@
name|Override
DECL|method|doStop ()
specifier|protected
name|void
name|doStop
parameter_list|()
throws|throws
name|Exception
block|{     }
annotation|@
name|ManagedOperation
argument_list|(
name|description
operator|=
literal|"Adds the key to the store"
argument_list|)
annotation|@
name|Override
DECL|method|add (final T key)
specifier|public
name|boolean
name|add
parameter_list|(
specifier|final
name|T
name|key
parameter_list|)
block|{
comment|// Run this in single transaction.
name|Boolean
name|rc
init|=
name|transactionTemplate
operator|.
name|execute
argument_list|(
operator|new
name|TransactionCallback
argument_list|<
name|Boolean
argument_list|>
argument_list|()
block|{
specifier|public
name|Boolean
name|doInTransaction
parameter_list|(
name|TransactionStatus
name|status
parameter_list|)
block|{
name|int
name|count
init|=
name|queryForInt
argument_list|(
name|key
argument_list|)
decl_stmt|;
if|if
condition|(
name|count
operator|==
literal|0
condition|)
block|{
name|insert
argument_list|(
name|key
argument_list|)
expr_stmt|;
return|return
name|Boolean
operator|.
name|TRUE
return|;
block|}
else|else
block|{
return|return
name|Boolean
operator|.
name|FALSE
return|;
block|}
block|}
block|}
argument_list|)
decl_stmt|;
return|return
name|rc
operator|.
name|booleanValue
argument_list|()
return|;
block|}
annotation|@
name|ManagedOperation
argument_list|(
name|description
operator|=
literal|"Does the store contain the given key"
argument_list|)
annotation|@
name|Override
DECL|method|contains (final T key)
specifier|public
name|boolean
name|contains
parameter_list|(
specifier|final
name|T
name|key
parameter_list|)
block|{
comment|// Run this in single transaction.
name|Boolean
name|rc
init|=
name|transactionTemplate
operator|.
name|execute
argument_list|(
operator|new
name|TransactionCallback
argument_list|<
name|Boolean
argument_list|>
argument_list|()
block|{
specifier|public
name|Boolean
name|doInTransaction
parameter_list|(
name|TransactionStatus
name|status
parameter_list|)
block|{
name|int
name|count
init|=
name|queryForInt
argument_list|(
name|key
argument_list|)
decl_stmt|;
if|if
condition|(
name|count
operator|==
literal|0
condition|)
block|{
return|return
name|Boolean
operator|.
name|FALSE
return|;
block|}
else|else
block|{
return|return
name|Boolean
operator|.
name|TRUE
return|;
block|}
block|}
block|}
argument_list|)
decl_stmt|;
return|return
name|rc
operator|.
name|booleanValue
argument_list|()
return|;
block|}
annotation|@
name|ManagedOperation
argument_list|(
name|description
operator|=
literal|"Remove the key from the store"
argument_list|)
annotation|@
name|Override
DECL|method|remove (final T key)
specifier|public
name|boolean
name|remove
parameter_list|(
specifier|final
name|T
name|key
parameter_list|)
block|{
name|Boolean
name|rc
init|=
name|transactionTemplate
operator|.
name|execute
argument_list|(
operator|new
name|TransactionCallback
argument_list|<
name|Boolean
argument_list|>
argument_list|()
block|{
specifier|public
name|Boolean
name|doInTransaction
parameter_list|(
name|TransactionStatus
name|status
parameter_list|)
block|{
name|int
name|updateCount
init|=
name|delete
argument_list|(
name|key
argument_list|)
decl_stmt|;
if|if
condition|(
name|updateCount
operator|==
literal|0
condition|)
block|{
return|return
name|Boolean
operator|.
name|FALSE
return|;
block|}
else|else
block|{
return|return
name|Boolean
operator|.
name|TRUE
return|;
block|}
block|}
block|}
argument_list|)
decl_stmt|;
return|return
name|rc
operator|.
name|booleanValue
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|confirm (final T key)
specifier|public
name|boolean
name|confirm
parameter_list|(
specifier|final
name|T
name|key
parameter_list|)
block|{
return|return
literal|true
return|;
block|}
DECL|method|getJdbcTemplate ()
specifier|public
name|JdbcTemplate
name|getJdbcTemplate
parameter_list|()
block|{
return|return
name|jdbcTemplate
return|;
block|}
DECL|method|setJdbcTemplate (JdbcTemplate jdbcTemplate)
specifier|public
name|void
name|setJdbcTemplate
parameter_list|(
name|JdbcTemplate
name|jdbcTemplate
parameter_list|)
block|{
name|this
operator|.
name|jdbcTemplate
operator|=
name|jdbcTemplate
expr_stmt|;
block|}
DECL|method|getProcessorName ()
specifier|public
name|String
name|getProcessorName
parameter_list|()
block|{
return|return
name|processorName
return|;
block|}
DECL|method|setProcessorName (String processorName)
specifier|public
name|void
name|setProcessorName
parameter_list|(
name|String
name|processorName
parameter_list|)
block|{
name|this
operator|.
name|processorName
operator|=
name|processorName
expr_stmt|;
block|}
DECL|method|getTransactionTemplate ()
specifier|public
name|TransactionTemplate
name|getTransactionTemplate
parameter_list|()
block|{
return|return
name|transactionTemplate
return|;
block|}
DECL|method|setTransactionTemplate (TransactionTemplate transactionTemplate)
specifier|public
name|void
name|setTransactionTemplate
parameter_list|(
name|TransactionTemplate
name|transactionTemplate
parameter_list|)
block|{
name|this
operator|.
name|transactionTemplate
operator|=
name|transactionTemplate
expr_stmt|;
block|}
DECL|method|getDataSource ()
specifier|public
name|DataSource
name|getDataSource
parameter_list|()
block|{
return|return
name|dataSource
return|;
block|}
DECL|method|setDataSource (DataSource dataSource)
specifier|public
name|void
name|setDataSource
parameter_list|(
name|DataSource
name|dataSource
parameter_list|)
block|{
name|this
operator|.
name|dataSource
operator|=
name|dataSource
expr_stmt|;
block|}
block|}
end_class

end_unit

