begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.foo.salesforce.contact.springboot
package|package
name|org
operator|.
name|foo
operator|.
name|salesforce
operator|.
name|contact
operator|.
name|springboot
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Generated
import|;
end_import

begin_comment
comment|/**  * The salesforce connector is used for integrating Camel with the massive  * Salesforce API.  *   * Generated by camel-package-maven-plugin - do not edit this file!  */
end_comment

begin_class
annotation|@
name|Generated
argument_list|(
literal|"org.apache.camel.maven.connector.SpringBootAutoConfigurationMojo"
argument_list|)
DECL|class|SalesforceUpsertContactConnectorConfigurationCommon
specifier|public
class|class
name|SalesforceUpsertContactConnectorConfigurationCommon
block|{
comment|/**      * URL of the Salesforce instance used for authentication by default set to      * https://login.salesforce.com      */
DECL|field|loginUrl
specifier|private
name|String
name|loginUrl
init|=
literal|"https://login.salesforce.com"
decl_stmt|;
comment|/**      * OAuth Consumer Key of the connected app configured in the Salesforce      * instance setup. Typically a connected app needs to be configured but one      * can be provided by installing a package.      */
DECL|field|clientId
specifier|private
name|String
name|clientId
decl_stmt|;
comment|/**      * OAuth Consumer Secret of the connected app configured in the Salesforce      * instance setup.      */
DECL|field|clientSecret
specifier|private
name|String
name|clientSecret
decl_stmt|;
comment|/**      * Refresh token already obtained in the refresh token OAuth flow. One needs      * to setup a web application and configure a callback URL to receive the      * refresh token or configure using the builtin callback at      * https://login.salesforce.com/services/oauth2/success or      * https://test.salesforce.com/services/oauth2/success and then retrive the      * refresh_token from the URL at the end of the flow. Note that in      * development organizations Salesforce allows hosting the callback web      * application at localhost.      */
DECL|field|refreshToken
specifier|private
name|String
name|refreshToken
decl_stmt|;
comment|/**      * SObject external ID field name      */
DECL|field|sObjectIdName
specifier|private
name|String
name|sObjectIdName
decl_stmt|;
comment|/**      * SObject external ID field value      */
DECL|field|sObjectIdValue
specifier|private
name|String
name|sObjectIdValue
decl_stmt|;
DECL|method|getLoginUrl ()
specifier|public
name|String
name|getLoginUrl
parameter_list|()
block|{
return|return
name|loginUrl
return|;
block|}
DECL|method|setLoginUrl (String loginUrl)
specifier|public
name|void
name|setLoginUrl
parameter_list|(
name|String
name|loginUrl
parameter_list|)
block|{
name|this
operator|.
name|loginUrl
operator|=
name|loginUrl
expr_stmt|;
block|}
DECL|method|getClientId ()
specifier|public
name|String
name|getClientId
parameter_list|()
block|{
return|return
name|clientId
return|;
block|}
DECL|method|setClientId (String clientId)
specifier|public
name|void
name|setClientId
parameter_list|(
name|String
name|clientId
parameter_list|)
block|{
name|this
operator|.
name|clientId
operator|=
name|clientId
expr_stmt|;
block|}
DECL|method|getClientSecret ()
specifier|public
name|String
name|getClientSecret
parameter_list|()
block|{
return|return
name|clientSecret
return|;
block|}
DECL|method|setClientSecret (String clientSecret)
specifier|public
name|void
name|setClientSecret
parameter_list|(
name|String
name|clientSecret
parameter_list|)
block|{
name|this
operator|.
name|clientSecret
operator|=
name|clientSecret
expr_stmt|;
block|}
DECL|method|getRefreshToken ()
specifier|public
name|String
name|getRefreshToken
parameter_list|()
block|{
return|return
name|refreshToken
return|;
block|}
DECL|method|setRefreshToken (String refreshToken)
specifier|public
name|void
name|setRefreshToken
parameter_list|(
name|String
name|refreshToken
parameter_list|)
block|{
name|this
operator|.
name|refreshToken
operator|=
name|refreshToken
expr_stmt|;
block|}
DECL|method|getSObjectIdName ()
specifier|public
name|String
name|getSObjectIdName
parameter_list|()
block|{
return|return
name|sObjectIdName
return|;
block|}
DECL|method|setSObjectIdName (String sObjectIdName)
specifier|public
name|void
name|setSObjectIdName
parameter_list|(
name|String
name|sObjectIdName
parameter_list|)
block|{
name|this
operator|.
name|sObjectIdName
operator|=
name|sObjectIdName
expr_stmt|;
block|}
DECL|method|getSObjectIdValue ()
specifier|public
name|String
name|getSObjectIdValue
parameter_list|()
block|{
return|return
name|sObjectIdValue
return|;
block|}
DECL|method|setSObjectIdValue (String sObjectIdValue)
specifier|public
name|void
name|setSObjectIdValue
parameter_list|(
name|String
name|sObjectIdValue
parameter_list|)
block|{
name|this
operator|.
name|sObjectIdValue
operator|=
name|sObjectIdValue
expr_stmt|;
block|}
block|}
end_class

end_unit

