begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.salesforce.internal
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|salesforce
operator|.
name|internal
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|ExecutionException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|TimeoutException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|salesforce
operator|.
name|SalesforceHttpClient
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|salesforce
operator|.
name|SalesforceLoginConfig
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|salesforce
operator|.
name|api
operator|.
name|SalesforceException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
operator|.
name|DefaultCamelContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|support
operator|.
name|jsse
operator|.
name|KeyStoreParameters
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|client
operator|.
name|api
operator|.
name|ContentResponse
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|client
operator|.
name|api
operator|.
name|Request
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|http
operator|.
name|HttpStatus
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|ArgumentMatchers
operator|.
name|any
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|ArgumentMatchers
operator|.
name|anyLong
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|ArgumentMatchers
operator|.
name|eq
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|Mockito
operator|.
name|mock
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|Mockito
operator|.
name|when
import|;
end_import

begin_class
DECL|class|SalesforceSessionTest
specifier|public
class|class
name|SalesforceSessionTest
block|{
DECL|field|TIMEOUT
specifier|private
specifier|static
specifier|final
name|int
name|TIMEOUT
init|=
literal|1
decl_stmt|;
DECL|field|parameters
specifier|private
specifier|final
name|KeyStoreParameters
name|parameters
decl_stmt|;
DECL|method|SalesforceSessionTest ()
specifier|public
name|SalesforceSessionTest
parameter_list|()
block|{
name|parameters
operator|=
operator|new
name|KeyStoreParameters
argument_list|()
expr_stmt|;
name|parameters
operator|.
name|setResource
argument_list|(
literal|"test.p12"
argument_list|)
expr_stmt|;
name|parameters
operator|.
name|setType
argument_list|(
literal|"PKCS12"
argument_list|)
expr_stmt|;
name|parameters
operator|.
name|setPassword
argument_list|(
literal|"password"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|shouldGenerateJwtTokens ()
specifier|public
name|void
name|shouldGenerateJwtTokens
parameter_list|()
block|{
specifier|final
name|SalesforceLoginConfig
name|config
init|=
operator|new
name|SalesforceLoginConfig
argument_list|(
literal|"https://login.salesforce.com"
argument_list|,
literal|"ABCD"
argument_list|,
literal|"username"
argument_list|,
name|parameters
argument_list|,
literal|true
argument_list|)
decl_stmt|;
specifier|final
name|SalesforceSession
name|session
init|=
operator|new
name|SalesforceSession
argument_list|(
operator|new
name|DefaultCamelContext
argument_list|()
argument_list|,
name|mock
argument_list|(
name|SalesforceHttpClient
operator|.
name|class
argument_list|)
argument_list|,
name|TIMEOUT
argument_list|,
name|config
argument_list|)
decl_stmt|;
specifier|final
name|String
name|jwtAssertion
init|=
name|session
operator|.
name|generateJwtAssertion
argument_list|()
decl_stmt|;
name|Assert
operator|.
name|assertNotNull
argument_list|(
name|jwtAssertion
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|shouldUseTheOverridenInstanceUrl ()
specifier|public
name|void
name|shouldUseTheOverridenInstanceUrl
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|SalesforceLoginConfig
name|config
init|=
operator|new
name|SalesforceLoginConfig
argument_list|(
literal|"https://login.salesforce.com"
argument_list|,
literal|"clientId"
argument_list|,
literal|"clientSecret"
argument_list|,
literal|"username"
argument_list|,
literal|"password"
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|config
operator|.
name|setInstanceUrl
argument_list|(
literal|"https://custom.salesforce.com:8443"
argument_list|)
expr_stmt|;
specifier|final
name|SalesforceSession
name|session
init|=
name|login
argument_list|(
name|config
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"https://custom.salesforce.com:8443"
argument_list|,
name|session
operator|.
name|getInstanceUrl
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|shouldUseTheSalesforceSuppliedInstanceUrl ()
specifier|public
name|void
name|shouldUseTheSalesforceSuppliedInstanceUrl
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|SalesforceLoginConfig
name|config
init|=
operator|new
name|SalesforceLoginConfig
argument_list|(
literal|"https://login.salesforce.com"
argument_list|,
literal|"clientId"
argument_list|,
literal|"clientSecret"
argument_list|,
literal|"username"
argument_list|,
literal|"password"
argument_list|,
literal|true
argument_list|)
decl_stmt|;
specifier|final
name|SalesforceSession
name|session
init|=
name|login
argument_list|(
name|config
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"https://eu11.salesforce.com"
argument_list|,
name|session
operator|.
name|getInstanceUrl
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|method|login (final SalesforceLoginConfig config)
specifier|static
name|SalesforceSession
name|login
parameter_list|(
specifier|final
name|SalesforceLoginConfig
name|config
parameter_list|)
throws|throws
name|InterruptedException
throws|,
name|TimeoutException
throws|,
name|ExecutionException
throws|,
name|SalesforceException
block|{
specifier|final
name|SalesforceHttpClient
name|client
init|=
name|mock
argument_list|(
name|SalesforceHttpClient
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|final
name|SalesforceSession
name|session
init|=
operator|new
name|SalesforceSession
argument_list|(
operator|new
name|DefaultCamelContext
argument_list|()
argument_list|,
name|client
argument_list|,
name|TIMEOUT
argument_list|,
name|config
argument_list|)
decl_stmt|;
specifier|final
name|Request
name|request
init|=
name|mock
argument_list|(
name|Request
operator|.
name|class
argument_list|)
decl_stmt|;
name|when
argument_list|(
name|client
operator|.
name|POST
argument_list|(
name|eq
argument_list|(
literal|"https://login.salesforce.com/services/oauth2/token"
argument_list|)
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|request
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|request
operator|.
name|content
argument_list|(
name|any
argument_list|()
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|request
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|request
operator|.
name|timeout
argument_list|(
name|anyLong
argument_list|()
argument_list|,
name|any
argument_list|()
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|request
argument_list|)
expr_stmt|;
specifier|final
name|ContentResponse
name|response
init|=
name|mock
argument_list|(
name|ContentResponse
operator|.
name|class
argument_list|)
decl_stmt|;
name|when
argument_list|(
name|request
operator|.
name|send
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|response
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|response
operator|.
name|getStatus
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|HttpStatus
operator|.
name|OK_200
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|response
operator|.
name|getContentAsString
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"{\"instance_url\": \"https://eu11.salesforce.com\"}"
argument_list|)
expr_stmt|;
name|session
operator|.
name|login
argument_list|(
literal|null
argument_list|)
expr_stmt|;
return|return
name|session
return|;
block|}
block|}
end_class

end_unit

