begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.apache.camel.eclipse
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|eclipse
package|;
end_package

begin_import
import|import
name|org
operator|.
name|openarchitectureware
operator|.
name|xtext
operator|.
name|AbstractXtextEditorPlugin
import|;
end_import

begin_import
import|import
name|org
operator|.
name|openarchitectureware
operator|.
name|xtext
operator|.
name|LanguageUtilities
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|BundleContext
import|;
end_import

begin_class
DECL|class|camelEditorPlugin
specifier|public
class|class
name|camelEditorPlugin
extends|extends
name|AbstractXtextEditorPlugin
block|{
DECL|field|plugin
specifier|private
specifier|static
name|camelEditorPlugin
name|plugin
decl_stmt|;
DECL|method|getDefault ()
specifier|public
specifier|static
name|camelEditorPlugin
name|getDefault
parameter_list|()
block|{
return|return
name|plugin
return|;
block|}
DECL|field|utilities
specifier|private
name|camelUtilities
name|utilities
init|=
operator|new
name|camelUtilities
argument_list|()
decl_stmt|;
DECL|method|getUtilities ()
specifier|public
name|LanguageUtilities
name|getUtilities
parameter_list|()
block|{
return|return
name|utilities
return|;
block|}
DECL|method|camelEditorPlugin ()
specifier|public
name|camelEditorPlugin
parameter_list|()
block|{
name|plugin
operator|=
name|this
expr_stmt|;
block|}
DECL|method|stop (BundleContext context)
specifier|public
name|void
name|stop
parameter_list|(
name|BundleContext
name|context
parameter_list|)
throws|throws
name|Exception
block|{
name|super
operator|.
name|stop
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|plugin
operator|=
literal|null
expr_stmt|;
block|}
block|}
end_class

end_unit

