begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.impl
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Component
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|bean
operator|.
name|BeanComponent
import|;
end_import

begin_comment
comment|/**  * @version $Revision$  */
end_comment

begin_class
DECL|class|DefaultCamelContextTest
specifier|public
class|class
name|DefaultCamelContextTest
extends|extends
name|TestCase
block|{
DECL|method|testAutoCreateComponentsOn ()
specifier|public
name|void
name|testAutoCreateComponentsOn
parameter_list|()
block|{
name|DefaultCamelContext
name|ctx
init|=
operator|new
name|DefaultCamelContext
argument_list|()
decl_stmt|;
name|Component
name|component
init|=
name|ctx
operator|.
name|getComponent
argument_list|(
literal|"bean"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|component
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|component
operator|.
name|getClass
argument_list|()
argument_list|,
name|BeanComponent
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
DECL|method|testAutoCreateComponentsOff ()
specifier|public
name|void
name|testAutoCreateComponentsOff
parameter_list|()
block|{
name|DefaultCamelContext
name|ctx
init|=
operator|new
name|DefaultCamelContext
argument_list|()
decl_stmt|;
name|ctx
operator|.
name|setAutoCreateComponents
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|Component
name|component
init|=
name|ctx
operator|.
name|getComponent
argument_list|(
literal|"bean"
argument_list|)
decl_stmt|;
name|assertNull
argument_list|(
name|component
argument_list|)
expr_stmt|;
block|}
DECL|method|testGetComponents ()
specifier|public
name|void
name|testGetComponents
parameter_list|()
throws|throws
name|Exception
block|{
name|DefaultCamelContext
name|ctx
init|=
operator|new
name|DefaultCamelContext
argument_list|()
decl_stmt|;
name|Component
name|component
init|=
name|ctx
operator|.
name|getComponent
argument_list|(
literal|"bean"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|component
argument_list|)
expr_stmt|;
name|List
argument_list|<
name|String
argument_list|>
name|list
init|=
name|ctx
operator|.
name|getComponentNames
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|list
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"bean"
argument_list|,
name|list
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

