begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.itest.issues
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|itest
operator|.
name|issues
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|builder
operator|.
name|AdviceWithRouteBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|builder
operator|.
name|RouteBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|test
operator|.
name|junit4
operator|.
name|CamelTestSupport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
DECL|class|IsUseAdviceWithJUnit4Test
specifier|public
class|class
name|IsUseAdviceWithJUnit4Test
extends|extends
name|CamelTestSupport
block|{
DECL|field|providerEndPointURI
specifier|private
name|String
name|providerEndPointURI
init|=
literal|"http4://fakeeeeWebsite.com:80"
decl_stmt|;
DECL|field|timerEndPointURI
specifier|private
name|String
name|timerEndPointURI
init|=
literal|"timer://myTimer"
decl_stmt|;
DECL|field|mockEndPointURI
specifier|private
name|String
name|mockEndPointURI
init|=
literal|"mock:myMock"
decl_stmt|;
DECL|field|directEndPointURI
specifier|private
name|String
name|directEndPointURI
init|=
literal|"direct:myDirect"
decl_stmt|;
annotation|@
name|Override
DECL|method|createRouteBuilder ()
specifier|protected
name|RouteBuilder
name|createRouteBuilder
parameter_list|()
throws|throws
name|Exception
block|{
return|return
operator|new
name|RouteBuilder
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|configure
parameter_list|()
throws|throws
name|Exception
block|{
name|from
argument_list|(
name|timerEndPointURI
argument_list|)
operator|.
name|to
argument_list|(
name|providerEndPointURI
argument_list|)
operator|.
name|to
argument_list|(
name|mockEndPointURI
argument_list|)
expr_stmt|;
block|}
block|}
return|;
block|}
annotation|@
name|Test
DECL|method|testIsUseAdviceWith ()
specifier|public
name|void
name|testIsUseAdviceWith
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|getRouteDefinitions
argument_list|()
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|adviceWith
argument_list|(
name|context
argument_list|,
operator|new
name|AdviceWithRouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
throws|throws
name|Exception
block|{
name|replaceFromWith
argument_list|(
name|directEndPointURI
argument_list|)
expr_stmt|;
name|interceptSendToEndpoint
argument_list|(
name|providerEndPointURI
argument_list|)
operator|.
name|to
argument_list|(
literal|"mock:intercepted"
argument_list|)
operator|.
name|skipSendToOriginalEndpoint
argument_list|()
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
comment|// we must manually start when we are done with all the advice with
name|context
operator|.
name|start
argument_list|()
expr_stmt|;
name|getMockEndpoint
argument_list|(
name|mockEndPointURI
argument_list|)
operator|.
name|expectedBodiesReceived
argument_list|(
literal|"a trigger"
argument_list|)
expr_stmt|;
name|getMockEndpoint
argument_list|(
literal|"mock:intercepted"
argument_list|)
operator|.
name|expectedBodiesReceived
argument_list|(
literal|"a trigger"
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
name|directEndPointURI
argument_list|,
literal|"a trigger"
argument_list|)
expr_stmt|;
name|assertMockEndpointsSatisfied
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|context
operator|.
name|hasEndpoint
argument_list|(
name|directEndPointURI
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|context
operator|.
name|hasEndpoint
argument_list|(
name|mockEndPointURI
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|isUseAdviceWith ()
specifier|public
name|boolean
name|isUseAdviceWith
parameter_list|()
block|{
return|return
literal|true
return|;
block|}
annotation|@
name|Override
DECL|method|isUseRouteBuilder ()
specifier|public
name|boolean
name|isUseRouteBuilder
parameter_list|()
block|{
return|return
literal|true
return|;
block|}
block|}
end_class

end_unit

