begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.itest.springboot.util
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|itest
operator|.
name|springboot
operator|.
name|util
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|parsers
operator|.
name|DocumentBuilder
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|parsers
operator|.
name|DocumentBuilderFactory
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|xpath
operator|.
name|XPath
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|xpath
operator|.
name|XPathExpression
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|xpath
operator|.
name|XPathFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Document
import|;
end_import

begin_comment
comment|/**  * Resolves the currently used version of a library. Useful to run unit tests directly from the IDE, without passing additional parameters.  * It resolves surefire properties.  */
end_comment

begin_class
DECL|class|DependencyResolver
specifier|public
specifier|final
class|class
name|DependencyResolver
block|{
DECL|field|DEFAULT_PREFIX
specifier|private
specifier|static
specifier|final
name|String
name|DEFAULT_PREFIX
init|=
literal|"version_"
decl_stmt|;
DECL|field|factory
specifier|private
specifier|static
name|DocumentBuilderFactory
name|factory
init|=
name|DocumentBuilderFactory
operator|.
name|newInstance
argument_list|()
decl_stmt|;
DECL|field|xPathfactory
specifier|private
specifier|static
name|XPathFactory
name|xPathfactory
init|=
name|XPathFactory
operator|.
name|newInstance
argument_list|()
decl_stmt|;
DECL|method|DependencyResolver ()
specifier|private
name|DependencyResolver
parameter_list|()
block|{     }
comment|/**      * Gets a groupId and artifactId in the form "groupId:artifactId" and returns the current version from the pom.      * Uses {@link DependencyResolver#withVersion(String, String)} using a default prefix.      *      * @param groupArtifact the groupId and artifactId in the form "groupId:artifactId"      * @return the maven canonical form of the artifact "groupId:artifactId:version"      */
DECL|method|withVersion (String groupArtifact)
specifier|public
specifier|static
name|String
name|withVersion
parameter_list|(
name|String
name|groupArtifact
parameter_list|)
block|{
return|return
name|withVersion
argument_list|(
name|DEFAULT_PREFIX
argument_list|,
name|groupArtifact
argument_list|)
return|;
block|}
comment|/**      * Gets a groupId and artifactId in the form "groupId:artifactId" and returns the current version from the pom.      * Versions are resolved from system properties when using surefire, and by looking at the poms when running from IDE.      *      * @param prefix the prefix to use to lookup the property from surefire      * @param groupArtifact the groupId and artifactId in the form "groupId:artifactId"      * @return the maven canonical form of the artifact "groupId:artifactId:version"      */
DECL|method|withVersion (String prefix, String groupArtifact)
specifier|public
specifier|static
name|String
name|withVersion
parameter_list|(
name|String
name|prefix
parameter_list|,
name|String
name|groupArtifact
parameter_list|)
block|{
name|String
name|version
init|=
name|System
operator|.
name|getProperty
argument_list|(
name|prefix
operator|+
name|groupArtifact
argument_list|)
decl_stmt|;
try|try
block|{
if|if
condition|(
name|version
operator|==
literal|null
condition|)
block|{
comment|// Usually, when running from IDE
name|version
operator|=
name|resolveSurefireProperty
argument_list|(
name|prefix
operator|+
name|groupArtifact
argument_list|)
expr_stmt|;
block|}
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
comment|// cannot use logging libs
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"RESOLVER ERROR>> Error while retrieving version for artifact: "
operator|+
name|groupArtifact
argument_list|)
expr_stmt|;
name|e
operator|.
name|printStackTrace
argument_list|()
expr_stmt|;
return|return
name|groupArtifact
return|;
block|}
if|if
condition|(
name|version
operator|==
literal|null
condition|)
block|{
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"RESOLVER ERROR>> Cannot determine version for maven artifact: "
operator|+
name|groupArtifact
argument_list|)
expr_stmt|;
return|return
name|groupArtifact
return|;
block|}
elseif|else
if|if
condition|(
operator|!
name|isResolved
argument_list|(
name|version
argument_list|)
condition|)
block|{
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"RESOLVER ERROR>> Cannot resolve version for maven artifact: "
operator|+
name|groupArtifact
operator|+
literal|". Missing property value: "
operator|+
name|version
argument_list|)
expr_stmt|;
return|return
name|groupArtifact
return|;
block|}
return|return
name|groupArtifact
operator|+
literal|":"
operator|+
name|version
return|;
block|}
DECL|method|resolveSurefireProperty (String property)
specifier|private
specifier|static
name|String
name|resolveSurefireProperty
parameter_list|(
name|String
name|property
parameter_list|)
throws|throws
name|Exception
block|{
name|property
operator|=
name|getSurefirePropertyFromPom
argument_list|(
literal|"pom.xml"
argument_list|,
name|property
argument_list|)
expr_stmt|;
if|if
condition|(
name|property
operator|!=
literal|null
operator|&&
operator|!
name|isResolved
argument_list|(
name|property
argument_list|)
condition|)
block|{
name|property
operator|=
name|resolveProperty
argument_list|(
literal|"pom.xml"
argument_list|,
name|property
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|property
operator|!=
literal|null
operator|&&
operator|!
name|isResolved
argument_list|(
name|property
argument_list|)
condition|)
block|{
name|property
operator|=
name|resolveProperty
argument_list|(
literal|"../pom.xml"
argument_list|,
name|property
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|property
operator|!=
literal|null
operator|&&
operator|!
name|isResolved
argument_list|(
name|property
argument_list|)
condition|)
block|{
name|property
operator|=
name|resolveProperty
argument_list|(
literal|"../../parent/pom.xml"
argument_list|,
name|property
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
name|property
return|;
block|}
DECL|method|resolveProperty (String pom, String property, int depth)
specifier|private
specifier|static
name|String
name|resolveProperty
parameter_list|(
name|String
name|pom
parameter_list|,
name|String
name|property
parameter_list|,
name|int
name|depth
parameter_list|)
throws|throws
name|Exception
block|{
name|property
operator|=
name|property
operator|.
name|trim
argument_list|()
expr_stmt|;
if|if
condition|(
operator|!
name|property
operator|.
name|startsWith
argument_list|(
literal|"${"
argument_list|)
operator|||
operator|!
name|property
operator|.
name|endsWith
argument_list|(
literal|"}"
argument_list|)
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Wrong property reference: "
operator|+
name|property
argument_list|)
throw|;
block|}
name|String
name|res
decl_stmt|;
if|if
condition|(
name|property
operator|.
name|equals
argument_list|(
literal|"${project.version}"
argument_list|)
condition|)
block|{
name|res
operator|=
name|getParentVersion
argument_list|(
name|pom
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|String
name|p
init|=
name|property
operator|.
name|substring
argument_list|(
literal|2
argument_list|)
decl_stmt|;
name|p
operator|=
name|p
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|p
operator|.
name|length
argument_list|()
operator|-
literal|1
argument_list|)
expr_stmt|;
name|res
operator|=
name|getPropertyFromPom
argument_list|(
name|pom
argument_list|,
name|p
argument_list|)
expr_stmt|;
if|if
condition|(
name|res
operator|==
literal|null
condition|)
block|{
return|return
name|property
return|;
block|}
block|}
if|if
condition|(
name|res
operator|!=
literal|null
operator|&&
operator|!
name|isResolved
argument_list|(
name|res
argument_list|)
operator|&&
name|depth
operator|<
literal|5
condition|)
block|{
name|res
operator|=
name|resolveProperty
argument_list|(
name|pom
argument_list|,
name|res
argument_list|,
name|depth
operator|+
literal|1
argument_list|)
expr_stmt|;
block|}
return|return
name|res
return|;
block|}
DECL|method|getSurefirePropertyFromPom (String pom, String property)
specifier|private
specifier|static
name|String
name|getSurefirePropertyFromPom
parameter_list|(
name|String
name|pom
parameter_list|,
name|String
name|property
parameter_list|)
throws|throws
name|Exception
block|{
return|return
name|xpath
argument_list|(
name|pom
argument_list|,
literal|"//plugin[artifactId='maven-surefire-plugin']//systemProperties/property[name='"
operator|+
name|property
operator|+
literal|"']/value/text()"
argument_list|)
return|;
block|}
DECL|method|getPropertyFromPom (String pom, String property)
specifier|private
specifier|static
name|String
name|getPropertyFromPom
parameter_list|(
name|String
name|pom
parameter_list|,
name|String
name|property
parameter_list|)
throws|throws
name|Exception
block|{
return|return
name|xpath
argument_list|(
name|pom
argument_list|,
literal|"/project/properties/"
operator|+
name|property
operator|+
literal|"/text()"
argument_list|)
return|;
block|}
DECL|method|getParentVersion (String pom)
specifier|private
specifier|static
name|String
name|getParentVersion
parameter_list|(
name|String
name|pom
parameter_list|)
throws|throws
name|Exception
block|{
return|return
name|xpath
argument_list|(
name|pom
argument_list|,
literal|"/project/parent/version/text()"
argument_list|)
return|;
block|}
DECL|method|xpath (String pom, String expression)
specifier|private
specifier|static
name|String
name|xpath
parameter_list|(
name|String
name|pom
parameter_list|,
name|String
name|expression
parameter_list|)
throws|throws
name|Exception
block|{
name|DocumentBuilder
name|builder
init|=
name|factory
operator|.
name|newDocumentBuilder
argument_list|()
decl_stmt|;
name|Document
name|doc
init|=
name|builder
operator|.
name|parse
argument_list|(
name|pom
argument_list|)
decl_stmt|;
name|XPath
name|xpath
init|=
name|xPathfactory
operator|.
name|newXPath
argument_list|()
decl_stmt|;
name|XPathExpression
name|expr
init|=
name|xpath
operator|.
name|compile
argument_list|(
name|expression
argument_list|)
decl_stmt|;
name|String
name|res
init|=
name|expr
operator|.
name|evaluate
argument_list|(
name|doc
argument_list|)
decl_stmt|;
if|if
condition|(
name|res
operator|!=
literal|null
operator|&&
name|res
operator|.
name|trim
argument_list|()
operator|.
name|length
argument_list|()
operator|==
literal|0
condition|)
block|{
name|res
operator|=
literal|null
expr_stmt|;
block|}
return|return
name|res
return|;
block|}
DECL|method|isResolved (String value)
specifier|private
specifier|static
name|boolean
name|isResolved
parameter_list|(
name|String
name|value
parameter_list|)
block|{
return|return
name|value
operator|!=
literal|null
operator|&&
operator|!
name|value
operator|.
name|startsWith
argument_list|(
literal|"$"
argument_list|)
return|;
block|}
block|}
end_class

end_unit

