begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  *  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.cxf
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|cxf
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|CamelContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Consumer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Processor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Producer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
operator|.
name|DefaultConsumer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
operator|.
name|DefaultEndpoint
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
operator|.
name|DefaultProducer
import|;
end_import

begin_comment
comment|/**  * The endpoint in the service engine  *  * @version $Revision$  */
end_comment

begin_class
DECL|class|CxfEndpoint
specifier|public
class|class
name|CxfEndpoint
extends|extends
name|DefaultEndpoint
argument_list|<
name|CxfExchange
argument_list|>
block|{
DECL|field|binding
specifier|private
name|CxfBinding
name|binding
decl_stmt|;
DECL|method|CxfEndpoint (String uri, CamelContext camelContext)
specifier|protected
name|CxfEndpoint
parameter_list|(
name|String
name|uri
parameter_list|,
name|CamelContext
name|camelContext
parameter_list|)
block|{
name|super
argument_list|(
name|uri
argument_list|,
name|camelContext
argument_list|)
expr_stmt|;
block|}
DECL|method|createProducer ()
specifier|public
name|Producer
argument_list|<
name|CxfExchange
argument_list|>
name|createProducer
parameter_list|()
throws|throws
name|Exception
block|{
return|return
name|startService
argument_list|(
operator|new
name|DefaultProducer
argument_list|<
name|CxfExchange
argument_list|>
argument_list|(
name|this
argument_list|)
block|{
specifier|public
name|void
name|onExchange
parameter_list|(
name|CxfExchange
name|exchange
parameter_list|)
block|{
comment|// TODO send into CXF
block|}
block|}
argument_list|)
return|;
block|}
DECL|method|createConsumer (Processor<CxfExchange> processor)
specifier|public
name|Consumer
argument_list|<
name|CxfExchange
argument_list|>
name|createConsumer
parameter_list|(
name|Processor
argument_list|<
name|CxfExchange
argument_list|>
name|processor
parameter_list|)
throws|throws
name|Exception
block|{
return|return
name|startService
argument_list|(
operator|new
name|DefaultConsumer
argument_list|<
name|CxfExchange
argument_list|>
argument_list|(
name|this
argument_list|,
name|processor
argument_list|)
block|{         }
argument_list|)
return|;
block|}
DECL|method|createExchange ()
specifier|public
name|CxfExchange
name|createExchange
parameter_list|()
block|{
return|return
operator|new
name|CxfExchange
argument_list|(
name|getContext
argument_list|()
argument_list|,
name|getBinding
argument_list|()
argument_list|)
return|;
block|}
DECL|method|getBinding ()
specifier|public
name|CxfBinding
name|getBinding
parameter_list|()
block|{
if|if
condition|(
name|binding
operator|==
literal|null
condition|)
block|{
name|binding
operator|=
operator|new
name|CxfBinding
argument_list|()
expr_stmt|;
block|}
return|return
name|binding
return|;
block|}
DECL|method|setBinding (CxfBinding binding)
specifier|public
name|void
name|setBinding
parameter_list|(
name|CxfBinding
name|binding
parameter_list|)
block|{
name|this
operator|.
name|binding
operator|=
name|binding
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|doActivate ()
specifier|protected
name|void
name|doActivate
parameter_list|()
throws|throws
name|Exception
block|{
name|super
operator|.
name|doActivate
argument_list|()
expr_stmt|;
comment|// TODO process any inbound messages from CXF
name|Processor
argument_list|<
name|CxfExchange
argument_list|>
name|processor
init|=
name|getInboundProcessor
argument_list|()
decl_stmt|;
if|if
condition|(
name|processor
operator|!=
literal|null
condition|)
block|{          }
block|}
block|}
end_class

end_unit

