begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.maven.bom.generator
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|maven
operator|.
name|bom
operator|.
name|generator
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_comment
comment|/**  * A set of {@code ExternalBomConflictCheck} objects,  */
end_comment

begin_class
DECL|class|ExternalBomConflictCheckSet
specifier|public
class|class
name|ExternalBomConflictCheckSet
block|{
DECL|field|boms
specifier|private
name|Set
argument_list|<
name|ExternalBomConflictCheck
argument_list|>
name|boms
init|=
operator|new
name|HashSet
argument_list|<>
argument_list|()
decl_stmt|;
DECL|method|ExternalBomConflictCheckSet ()
specifier|public
name|ExternalBomConflictCheckSet
parameter_list|()
block|{     }
DECL|method|getBoms ()
specifier|public
name|Set
argument_list|<
name|ExternalBomConflictCheck
argument_list|>
name|getBoms
parameter_list|()
block|{
return|return
name|boms
return|;
block|}
DECL|method|setBoms (Set<ExternalBomConflictCheck> boms)
specifier|public
name|void
name|setBoms
parameter_list|(
name|Set
argument_list|<
name|ExternalBomConflictCheck
argument_list|>
name|boms
parameter_list|)
block|{
name|this
operator|.
name|boms
operator|=
name|boms
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|toString ()
specifier|public
name|String
name|toString
parameter_list|()
block|{
specifier|final
name|StringBuilder
name|sb
init|=
operator|new
name|StringBuilder
argument_list|(
literal|"ExternalBomConflictCheckSet{"
argument_list|)
decl_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|"boms="
argument_list|)
operator|.
name|append
argument_list|(
name|boms
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|'}'
argument_list|)
expr_stmt|;
return|return
name|sb
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
end_class

end_unit

