begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.test.blueprint
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|test
operator|.
name|blueprint
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|seda
operator|.
name|SedaComponent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
DECL|class|BlueprintComponentPropertyPlaceholderTest
specifier|public
class|class
name|BlueprintComponentPropertyPlaceholderTest
extends|extends
name|CamelBlueprintTestSupport
block|{
annotation|@
name|Override
DECL|method|getBlueprintDescriptor ()
specifier|protected
name|String
name|getBlueprintDescriptor
parameter_list|()
block|{
return|return
literal|"org/apache/camel/test/blueprint/BlueprintComponentPropertyPlaceholderTest.xml"
return|;
block|}
annotation|@
name|Test
DECL|method|testComponentPropertyPlaceholder ()
specifier|public
name|void
name|testComponentPropertyPlaceholder
parameter_list|()
throws|throws
name|Exception
block|{
name|SedaComponent
name|myseda
init|=
operator|(
name|SedaComponent
operator|)
name|context
operator|.
name|getComponent
argument_list|(
literal|"myseda"
argument_list|,
literal|false
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|myseda
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|myseda
operator|.
name|getQueueSize
argument_list|()
argument_list|)
expr_stmt|;
comment|// test that the custom component works
name|int
name|before
init|=
name|myseda
operator|.
name|getQueueReference
argument_list|(
literal|"myseda://foo"
argument_list|)
operator|.
name|getQueue
argument_list|()
operator|.
name|size
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|0
argument_list|,
name|before
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
literal|"Hello World"
argument_list|)
expr_stmt|;
name|int
name|after
init|=
name|myseda
operator|.
name|getQueueReference
argument_list|(
literal|"myseda://foo"
argument_list|)
operator|.
name|getQueue
argument_list|()
operator|.
name|size
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|after
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

