begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.impl
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|ByteArrayInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|ContextTestSupport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Exchange
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|util
operator|.
name|xml
operator|.
name|StringSource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|builder
operator|.
name|RouteBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|mock
operator|.
name|MockEndpoint
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
DECL|class|LogDebugBodyStreamsTest
specifier|public
class|class
name|LogDebugBodyStreamsTest
extends|extends
name|ContextTestSupport
block|{
annotation|@
name|Override
DECL|method|createRegistry ()
specifier|protected
name|JndiRegistry
name|createRegistry
parameter_list|()
throws|throws
name|Exception
block|{
name|JndiRegistry
name|jndi
init|=
name|super
operator|.
name|createRegistry
argument_list|()
decl_stmt|;
name|jndi
operator|.
name|bind
argument_list|(
literal|"logFormatter"
argument_list|,
operator|new
name|TraceExchangeFormatter
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|jndi
return|;
block|}
annotation|@
name|Test
DECL|method|testLogBodyStreamStringSourceDisabled ()
specifier|public
name|void
name|testLogBodyStreamStringSourceDisabled
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|getGlobalOptions
argument_list|()
operator|.
name|put
argument_list|(
name|Exchange
operator|.
name|LOG_DEBUG_BODY_STREAMS
argument_list|,
literal|"false"
argument_list|)
expr_stmt|;
name|StringSource
name|body
init|=
operator|new
name|StringSource
argument_list|(
literal|"<?xml version=\"1.0\"?><person><name>Claus</name></person>"
argument_list|)
decl_stmt|;
name|MockEndpoint
name|mock
init|=
name|getMockEndpoint
argument_list|(
literal|"mock:result"
argument_list|)
decl_stmt|;
name|mock
operator|.
name|expectedMessageCount
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
name|body
argument_list|)
expr_stmt|;
name|assertMockEndpointsSatisfied
argument_list|()
expr_stmt|;
comment|// should be logged anyway
name|TraceExchangeFormatter
name|myFormatter
init|=
name|context
operator|.
name|getRegistry
argument_list|()
operator|.
name|lookupByNameAndType
argument_list|(
literal|"logFormatter"
argument_list|,
name|TraceExchangeFormatter
operator|.
name|class
argument_list|)
decl_stmt|;
name|String
name|msg
init|=
name|myFormatter
operator|.
name|getMessage
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|msg
operator|.
name|endsWith
argument_list|(
literal|"Body:<?xml version=\"1.0\"?><person><name>Claus</name></person>]"
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testLogBodyStreamStringSourceDisabledByDefault ()
specifier|public
name|void
name|testLogBodyStreamStringSourceDisabledByDefault
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|getGlobalOptions
argument_list|()
operator|.
name|remove
argument_list|(
name|Exchange
operator|.
name|LOG_DEBUG_BODY_STREAMS
argument_list|)
expr_stmt|;
name|StringSource
name|body
init|=
operator|new
name|StringSource
argument_list|(
literal|"<?xml version=\"1.0\"?><person><name>Claus</name></person>"
argument_list|)
decl_stmt|;
name|MockEndpoint
name|mock
init|=
name|getMockEndpoint
argument_list|(
literal|"mock:result"
argument_list|)
decl_stmt|;
name|mock
operator|.
name|expectedMessageCount
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
name|body
argument_list|)
expr_stmt|;
name|assertMockEndpointsSatisfied
argument_list|()
expr_stmt|;
comment|// should be logged anyway
name|TraceExchangeFormatter
name|myFormatter
init|=
name|context
operator|.
name|getRegistry
argument_list|()
operator|.
name|lookupByNameAndType
argument_list|(
literal|"logFormatter"
argument_list|,
name|TraceExchangeFormatter
operator|.
name|class
argument_list|)
decl_stmt|;
name|String
name|msg
init|=
name|myFormatter
operator|.
name|getMessage
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|msg
operator|.
name|endsWith
argument_list|(
literal|"Body:<?xml version=\"1.0\"?><person><name>Claus</name></person>]"
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testLogBodyStreamStringSourceEnabled ()
specifier|public
name|void
name|testLogBodyStreamStringSourceEnabled
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|getGlobalOptions
argument_list|()
operator|.
name|put
argument_list|(
name|Exchange
operator|.
name|LOG_DEBUG_BODY_STREAMS
argument_list|,
literal|"true"
argument_list|)
expr_stmt|;
name|StringSource
name|body
init|=
operator|new
name|StringSource
argument_list|(
literal|"<?xml version=\"1.0\"?><person><name>Claus</name></person>"
argument_list|)
decl_stmt|;
name|MockEndpoint
name|mock
init|=
name|getMockEndpoint
argument_list|(
literal|"mock:result"
argument_list|)
decl_stmt|;
name|mock
operator|.
name|expectedMessageCount
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
name|body
argument_list|)
expr_stmt|;
name|assertMockEndpointsSatisfied
argument_list|()
expr_stmt|;
comment|// should be logged anyway
name|TraceExchangeFormatter
name|myFormatter
init|=
name|context
operator|.
name|getRegistry
argument_list|()
operator|.
name|lookupByNameAndType
argument_list|(
literal|"logFormatter"
argument_list|,
name|TraceExchangeFormatter
operator|.
name|class
argument_list|)
decl_stmt|;
name|String
name|msg
init|=
name|myFormatter
operator|.
name|getMessage
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|msg
operator|.
name|endsWith
argument_list|(
literal|"Body:<?xml version=\"1.0\"?><person><name>Claus</name></person>]"
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testLogBodyStreamDisabled ()
specifier|public
name|void
name|testLogBodyStreamDisabled
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|getGlobalOptions
argument_list|()
operator|.
name|put
argument_list|(
name|Exchange
operator|.
name|LOG_DEBUG_BODY_STREAMS
argument_list|,
literal|"false"
argument_list|)
expr_stmt|;
name|InputStream
name|body
init|=
operator|new
name|ByteArrayInputStream
argument_list|(
literal|"Hello World"
operator|.
name|getBytes
argument_list|()
argument_list|)
decl_stmt|;
name|MockEndpoint
name|mock
init|=
name|getMockEndpoint
argument_list|(
literal|"mock:result"
argument_list|)
decl_stmt|;
name|mock
operator|.
name|expectedMessageCount
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
name|body
argument_list|)
expr_stmt|;
name|assertMockEndpointsSatisfied
argument_list|()
expr_stmt|;
comment|// should NOT be logged
name|TraceExchangeFormatter
name|myFormatter
init|=
name|context
operator|.
name|getRegistry
argument_list|()
operator|.
name|lookupByNameAndType
argument_list|(
literal|"logFormatter"
argument_list|,
name|TraceExchangeFormatter
operator|.
name|class
argument_list|)
decl_stmt|;
name|String
name|msg
init|=
name|myFormatter
operator|.
name|getMessage
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|msg
operator|.
name|endsWith
argument_list|(
literal|"Body: [Body is instance of java.io.InputStream]]"
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testLogBodyStreamDisabledByDefault ()
specifier|public
name|void
name|testLogBodyStreamDisabledByDefault
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|getGlobalOptions
argument_list|()
operator|.
name|remove
argument_list|(
name|Exchange
operator|.
name|LOG_DEBUG_BODY_STREAMS
argument_list|)
expr_stmt|;
name|InputStream
name|body
init|=
operator|new
name|ByteArrayInputStream
argument_list|(
literal|"Hello World"
operator|.
name|getBytes
argument_list|()
argument_list|)
decl_stmt|;
name|MockEndpoint
name|mock
init|=
name|getMockEndpoint
argument_list|(
literal|"mock:result"
argument_list|)
decl_stmt|;
name|mock
operator|.
name|expectedMessageCount
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
name|body
argument_list|)
expr_stmt|;
name|assertMockEndpointsSatisfied
argument_list|()
expr_stmt|;
comment|// should NOT be logged
name|TraceExchangeFormatter
name|myFormatter
init|=
name|context
operator|.
name|getRegistry
argument_list|()
operator|.
name|lookupByNameAndType
argument_list|(
literal|"logFormatter"
argument_list|,
name|TraceExchangeFormatter
operator|.
name|class
argument_list|)
decl_stmt|;
name|String
name|msg
init|=
name|myFormatter
operator|.
name|getMessage
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|msg
operator|.
name|endsWith
argument_list|(
literal|"Body: [Body is instance of java.io.InputStream]]"
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testLogBodyStreamEnabled ()
specifier|public
name|void
name|testLogBodyStreamEnabled
parameter_list|()
throws|throws
name|Exception
block|{
name|context
operator|.
name|getGlobalOptions
argument_list|()
operator|.
name|put
argument_list|(
name|Exchange
operator|.
name|LOG_DEBUG_BODY_STREAMS
argument_list|,
literal|"true"
argument_list|)
expr_stmt|;
name|InputStream
name|body
init|=
operator|new
name|ByteArrayInputStream
argument_list|(
literal|"Hello World"
operator|.
name|getBytes
argument_list|()
argument_list|)
decl_stmt|;
name|MockEndpoint
name|mock
init|=
name|getMockEndpoint
argument_list|(
literal|"mock:result"
argument_list|)
decl_stmt|;
name|mock
operator|.
name|expectedMessageCount
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|template
operator|.
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
name|body
argument_list|)
expr_stmt|;
name|assertMockEndpointsSatisfied
argument_list|()
expr_stmt|;
comment|// should be logged
name|TraceExchangeFormatter
name|myFormatter
init|=
name|context
operator|.
name|getRegistry
argument_list|()
operator|.
name|lookupByNameAndType
argument_list|(
literal|"logFormatter"
argument_list|,
name|TraceExchangeFormatter
operator|.
name|class
argument_list|)
decl_stmt|;
name|String
name|msg
init|=
name|myFormatter
operator|.
name|getMessage
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|msg
operator|.
name|endsWith
argument_list|(
literal|"Body: [Body is instance of java.io.InputStream]]"
argument_list|)
argument_list|)
expr_stmt|;
name|assertIsInstanceOf
argument_list|(
name|InputStream
operator|.
name|class
argument_list|,
name|mock
operator|.
name|getReceivedExchanges
argument_list|()
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|getIn
argument_list|()
operator|.
name|getBody
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|createRouteBuilder ()
specifier|protected
name|RouteBuilder
name|createRouteBuilder
parameter_list|()
throws|throws
name|Exception
block|{
return|return
operator|new
name|RouteBuilder
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|configure
parameter_list|()
throws|throws
name|Exception
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|to
argument_list|(
literal|"log:foo"
argument_list|)
operator|.
name|to
argument_list|(
literal|"mock:result"
argument_list|)
expr_stmt|;
block|}
block|}
return|;
block|}
block|}
end_class

end_unit

