begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.foo.connector.springboot
package|package
name|org
operator|.
name|foo
operator|.
name|connector
operator|.
name|springboot
package|;
end_package

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URI
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Generated
import|;
end_import

begin_comment
comment|/**  * An awesome REST endpoint backed by Swagger specifications.  *   * Generated by camel-package-maven-plugin - do not edit this file!  */
end_comment

begin_class
annotation|@
name|Generated
argument_list|(
literal|"org.apache.camel.maven.connector.SpringBootAutoConfigurationMojo"
argument_list|)
DECL|class|PetStoreConnectorConfigurationCommon
specifier|public
class|class
name|PetStoreConnectorConfigurationCommon
block|{
comment|/**      * Path to the Swagger specification file. The scheme host base path are      * taken from this specification but these can be overriden with properties      * on the component or endpoint level. If not given the component tries to      * load swagger.json resource. Note that the host defined on the component      * and endpoint of this Component should contain the scheme hostname and      * optionally the port in the URI syntax (i.e.      * https://api.example.com:8080). Can be overriden in endpoint      * configuration.      */
DECL|field|specificationUri
specifier|private
name|URI
name|specificationUri
decl_stmt|;
comment|/**      * ID of the operation from the Swagger specification.      */
DECL|field|operationId
specifier|private
name|String
name|operationId
decl_stmt|;
DECL|method|getSpecificationUri ()
specifier|public
name|URI
name|getSpecificationUri
parameter_list|()
block|{
return|return
name|specificationUri
return|;
block|}
DECL|method|setSpecificationUri (URI specificationUri)
specifier|public
name|void
name|setSpecificationUri
parameter_list|(
name|URI
name|specificationUri
parameter_list|)
block|{
name|this
operator|.
name|specificationUri
operator|=
name|specificationUri
expr_stmt|;
block|}
DECL|method|getOperationId ()
specifier|public
name|String
name|getOperationId
parameter_list|()
block|{
return|return
name|operationId
return|;
block|}
DECL|method|setOperationId (String operationId)
specifier|public
name|void
name|setOperationId
parameter_list|(
name|String
name|operationId
parameter_list|)
block|{
name|this
operator|.
name|operationId
operator|=
name|operationId
expr_stmt|;
block|}
block|}
end_class

end_unit

