begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.dataformat.barcode.springboot
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|dataformat
operator|.
name|barcode
operator|.
name|springboot
package|;
end_package

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|boot
operator|.
name|context
operator|.
name|properties
operator|.
name|ConfigurationProperties
import|;
end_import

begin_comment
comment|/**  * Camel Barcode (e.g. QRcode, PDF417, DataMatrix) support  *   * Generated by camel-package-maven-plugin - do not edit this file!  */
end_comment

begin_class
annotation|@
name|ConfigurationProperties
argument_list|(
name|prefix
operator|=
literal|"camel.dataformat.barcode"
argument_list|)
DECL|class|BarcodeDataFormatConfiguration
specifier|public
class|class
name|BarcodeDataFormatConfiguration
block|{
comment|/**      * Width of the barcode      */
DECL|field|width
specifier|private
name|Integer
name|width
decl_stmt|;
comment|/**      * Height of the barcode      */
DECL|field|height
specifier|private
name|Integer
name|height
decl_stmt|;
comment|/**      * Image type of the barcode such as png      */
DECL|field|imageType
specifier|private
name|String
name|imageType
decl_stmt|;
comment|/**      * Barcode format such as QR-Code      */
DECL|field|barcodeFormat
specifier|private
name|String
name|barcodeFormat
decl_stmt|;
comment|/**      * Sets the value of the id property.      */
DECL|field|id
specifier|private
name|String
name|id
decl_stmt|;
DECL|method|getWidth ()
specifier|public
name|Integer
name|getWidth
parameter_list|()
block|{
return|return
name|width
return|;
block|}
DECL|method|setWidth (Integer width)
specifier|public
name|void
name|setWidth
parameter_list|(
name|Integer
name|width
parameter_list|)
block|{
name|this
operator|.
name|width
operator|=
name|width
expr_stmt|;
block|}
DECL|method|getHeight ()
specifier|public
name|Integer
name|getHeight
parameter_list|()
block|{
return|return
name|height
return|;
block|}
DECL|method|setHeight (Integer height)
specifier|public
name|void
name|setHeight
parameter_list|(
name|Integer
name|height
parameter_list|)
block|{
name|this
operator|.
name|height
operator|=
name|height
expr_stmt|;
block|}
DECL|method|getImageType ()
specifier|public
name|String
name|getImageType
parameter_list|()
block|{
return|return
name|imageType
return|;
block|}
DECL|method|setImageType (String imageType)
specifier|public
name|void
name|setImageType
parameter_list|(
name|String
name|imageType
parameter_list|)
block|{
name|this
operator|.
name|imageType
operator|=
name|imageType
expr_stmt|;
block|}
DECL|method|getBarcodeFormat ()
specifier|public
name|String
name|getBarcodeFormat
parameter_list|()
block|{
return|return
name|barcodeFormat
return|;
block|}
DECL|method|setBarcodeFormat (String barcodeFormat)
specifier|public
name|void
name|setBarcodeFormat
parameter_list|(
name|String
name|barcodeFormat
parameter_list|)
block|{
name|this
operator|.
name|barcodeFormat
operator|=
name|barcodeFormat
expr_stmt|;
block|}
DECL|method|getId ()
specifier|public
name|String
name|getId
parameter_list|()
block|{
return|return
name|id
return|;
block|}
DECL|method|setId (String id)
specifier|public
name|void
name|setId
parameter_list|(
name|String
name|id
parameter_list|)
block|{
name|this
operator|.
name|id
operator|=
name|id
expr_stmt|;
block|}
block|}
end_class

end_unit

