begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.spring.boot
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|spring
operator|.
name|boot
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Resource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|CamelContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|ConsumerTemplate
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|ProducerTemplate
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|spring
operator|.
name|boot
operator|.
name|CamelNonInvasiveCamelContextTest
operator|.
name|TestApplication
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|runner
operator|.
name|RunWith
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|beans
operator|.
name|factory
operator|.
name|annotation
operator|.
name|Autowired
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|boot
operator|.
name|autoconfigure
operator|.
name|EnableAutoConfiguration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|boot
operator|.
name|test
operator|.
name|context
operator|.
name|SpringBootTest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|context
operator|.
name|annotation
operator|.
name|ImportResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|test
operator|.
name|annotation
operator|.
name|DirtiesContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|test
operator|.
name|context
operator|.
name|junit4
operator|.
name|SpringRunner
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertNotNull
import|;
end_import

begin_class
annotation|@
name|DirtiesContext
annotation|@
name|RunWith
argument_list|(
name|SpringRunner
operator|.
name|class
argument_list|)
annotation|@
name|EnableAutoConfiguration
annotation|@
name|SpringBootTest
argument_list|(
name|classes
operator|=
block|{
name|TestApplication
operator|.
name|class
block|,
name|CamelNonInvasiveCamelContextTest
operator|.
name|class
block|}
argument_list|)
DECL|class|CamelNonInvasiveCamelContextTest
specifier|public
class|class
name|CamelNonInvasiveCamelContextTest
block|{
comment|// Collaborators fixtures
annotation|@
name|Autowired
DECL|field|camelContext
name|CamelContext
name|camelContext
decl_stmt|;
annotation|@
name|Autowired
DECL|field|producerTemplate
name|ProducerTemplate
name|producerTemplate
decl_stmt|;
annotation|@
name|Resource
argument_list|(
name|name
operator|=
literal|"xmlProducerTemplate"
argument_list|)
DECL|field|xmlProducerTemplate
name|ProducerTemplate
name|xmlProducerTemplate
decl_stmt|;
annotation|@
name|Autowired
DECL|field|consumerTemplate
name|ConsumerTemplate
name|consumerTemplate
decl_stmt|;
annotation|@
name|Resource
argument_list|(
name|name
operator|=
literal|"xmlConsumerTemplate"
argument_list|)
DECL|field|xmlConsumerTemplate
name|ConsumerTemplate
name|xmlConsumerTemplate
decl_stmt|;
comment|// Tests
annotation|@
name|Test
DECL|method|shouldUseCamelContextFromXml ()
specifier|public
name|void
name|shouldUseCamelContextFromXml
parameter_list|()
block|{
name|assertNotNull
argument_list|(
name|camelContext
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"xmlCamelContext"
argument_list|,
name|camelContext
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|shouldUseProducerTemplateFromXml ()
specifier|public
name|void
name|shouldUseProducerTemplateFromXml
parameter_list|()
block|{
name|assertNotNull
argument_list|(
name|producerTemplate
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|xmlProducerTemplate
argument_list|,
name|producerTemplate
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|shouldUseConsumerTemplateFromXml ()
specifier|public
name|void
name|shouldUseConsumerTemplateFromXml
parameter_list|()
block|{
name|assertNotNull
argument_list|(
name|consumerTemplate
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|xmlConsumerTemplate
argument_list|,
name|consumerTemplate
argument_list|)
expr_stmt|;
block|}
annotation|@
name|ImportResource
argument_list|(
name|value
operator|=
block|{
literal|"classpath:externalCamelContext.xml"
block|}
argument_list|)
DECL|class|TestApplication
specifier|public
specifier|static
class|class
name|TestApplication
block|{      }
block|}
end_class

end_unit

