begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.file.remote
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|file
operator|.
name|remote
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|BindToRegistry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Exchange
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|file
operator|.
name|GenericFile
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|file
operator|.
name|GenericFileEndpoint
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|file
operator|.
name|GenericFileOperations
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|file
operator|.
name|GenericFileProcessStrategy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
DECL|class|FtpConsumerProcessStrategyTest
specifier|public
class|class
name|FtpConsumerProcessStrategyTest
extends|extends
name|FtpServerTestSupport
block|{
annotation|@
name|BindToRegistry
argument_list|(
literal|"myStrategy"
argument_list|)
DECL|field|myStrategy
specifier|private
name|MyStrategy
name|myStrategy
init|=
operator|new
name|MyStrategy
argument_list|()
decl_stmt|;
DECL|method|getFtpUrl ()
specifier|private
name|String
name|getFtpUrl
parameter_list|()
block|{
return|return
literal|"ftp://admin@localhost:"
operator|+
name|getPort
argument_list|()
operator|+
literal|"/"
operator|+
name|FTP_ROOT_DIR
operator|+
literal|"?password=admin&processStrategy=#myStrategy"
return|;
block|}
annotation|@
name|Test
DECL|method|testFtpConsume ()
specifier|public
name|void
name|testFtpConsume
parameter_list|()
throws|throws
name|Exception
block|{
if|if
condition|(
operator|!
name|canTest
argument_list|()
condition|)
block|{
return|return;
block|}
name|sendFile
argument_list|(
name|getFtpUrl
argument_list|()
argument_list|,
literal|"Hello World"
argument_list|,
literal|"hello.txt"
argument_list|)
expr_stmt|;
name|String
name|out
init|=
name|consumer
operator|.
name|receiveBody
argument_list|(
name|getFtpUrl
argument_list|()
argument_list|,
literal|5000
argument_list|,
name|String
operator|.
name|class
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|out
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|out
operator|.
name|startsWith
argument_list|(
literal|"Hello World"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"Begin should have been invoked 1 times"
argument_list|,
literal|1
argument_list|,
name|myStrategy
operator|.
name|getInvoked
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|class|MyStrategy
specifier|private
specifier|static
class|class
name|MyStrategy
implements|implements
name|GenericFileProcessStrategy
block|{
DECL|field|invoked
specifier|private
specifier|volatile
name|int
name|invoked
decl_stmt|;
annotation|@
name|Override
DECL|method|prepareOnStartup (GenericFileOperations operations, GenericFileEndpoint endpoint)
specifier|public
name|void
name|prepareOnStartup
parameter_list|(
name|GenericFileOperations
name|operations
parameter_list|,
name|GenericFileEndpoint
name|endpoint
parameter_list|)
throws|throws
name|Exception
block|{
comment|// noop
block|}
annotation|@
name|Override
DECL|method|begin (GenericFileOperations operations, GenericFileEndpoint endpoint, Exchange exchange, GenericFile file)
specifier|public
name|boolean
name|begin
parameter_list|(
name|GenericFileOperations
name|operations
parameter_list|,
name|GenericFileEndpoint
name|endpoint
parameter_list|,
name|Exchange
name|exchange
parameter_list|,
name|GenericFile
name|file
parameter_list|)
throws|throws
name|Exception
block|{
return|return
literal|true
return|;
block|}
annotation|@
name|Override
DECL|method|abort (GenericFileOperations operations, GenericFileEndpoint endpoint, Exchange exchange, GenericFile file)
specifier|public
name|void
name|abort
parameter_list|(
name|GenericFileOperations
name|operations
parameter_list|,
name|GenericFileEndpoint
name|endpoint
parameter_list|,
name|Exchange
name|exchange
parameter_list|,
name|GenericFile
name|file
parameter_list|)
throws|throws
name|Exception
block|{
comment|// noop
block|}
annotation|@
name|Override
DECL|method|commit (GenericFileOperations operations, GenericFileEndpoint endpoint, Exchange exchange, GenericFile file)
specifier|public
name|void
name|commit
parameter_list|(
name|GenericFileOperations
name|operations
parameter_list|,
name|GenericFileEndpoint
name|endpoint
parameter_list|,
name|Exchange
name|exchange
parameter_list|,
name|GenericFile
name|file
parameter_list|)
throws|throws
name|Exception
block|{
name|invoked
operator|++
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|rollback (GenericFileOperations operations, GenericFileEndpoint endpoint, Exchange exchange, GenericFile file)
specifier|public
name|void
name|rollback
parameter_list|(
name|GenericFileOperations
name|operations
parameter_list|,
name|GenericFileEndpoint
name|endpoint
parameter_list|,
name|Exchange
name|exchange
parameter_list|,
name|GenericFile
name|file
parameter_list|)
throws|throws
name|Exception
block|{
comment|// noop
block|}
DECL|method|getInvoked ()
name|int
name|getInvoked
parameter_list|()
block|{
return|return
name|invoked
return|;
block|}
block|}
block|}
end_class

end_unit

