begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.geocoder
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|geocoder
package|;
end_package

begin_enum
DECL|enum|GeocoderStatus
specifier|public
enum|enum
name|GeocoderStatus
block|{
DECL|enumConstant|ERROR
name|ERROR
block|,
DECL|enumConstant|INVALID_REQUEST
name|INVALID_REQUEST
block|,
DECL|enumConstant|ACCESS_NOT_CONFIGURED
name|ACCESS_NOT_CONFIGURED
block|,
DECL|enumConstant|OK
name|OK
block|,
DECL|enumConstant|OVER_QUERY_LIMIT
name|OVER_QUERY_LIMIT
block|,
DECL|enumConstant|OVER_DAILY_LIMIT
name|OVER_DAILY_LIMIT
block|,
DECL|enumConstant|REQUEST_DENIED
name|REQUEST_DENIED
block|,
DECL|enumConstant|UNKNOWN_ERROR
name|UNKNOWN_ERROR
block|,
DECL|enumConstant|ZERO_RESULTS
name|ZERO_RESULTS
block|;
DECL|method|value ()
specifier|public
name|String
name|value
parameter_list|()
block|{
return|return
name|name
argument_list|()
return|;
block|}
DECL|method|fromValue (String v)
specifier|public
specifier|static
name|GeocoderStatus
name|fromValue
parameter_list|(
name|String
name|v
parameter_list|)
block|{
return|return
name|valueOf
argument_list|(
name|v
argument_list|)
return|;
block|}
block|}
end_enum

end_unit

