begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.kubernetes.cluster.lock
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|kubernetes
operator|.
name|cluster
operator|.
name|lock
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Date
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|util
operator|.
name|ObjectHelper
import|;
end_import

begin_comment
comment|/**  * Overview of a leadership status.  */
end_comment

begin_class
DECL|class|LeaderInfo
specifier|public
class|class
name|LeaderInfo
block|{
DECL|field|groupName
specifier|private
name|String
name|groupName
decl_stmt|;
DECL|field|leader
specifier|private
name|String
name|leader
decl_stmt|;
DECL|field|localTimestamp
specifier|private
name|Date
name|localTimestamp
decl_stmt|;
DECL|field|members
specifier|private
name|Set
argument_list|<
name|String
argument_list|>
name|members
decl_stmt|;
DECL|method|LeaderInfo ()
specifier|public
name|LeaderInfo
parameter_list|()
block|{     }
DECL|method|LeaderInfo (String groupName, String leader, Date timestamp, Set<String> members)
specifier|public
name|LeaderInfo
parameter_list|(
name|String
name|groupName
parameter_list|,
name|String
name|leader
parameter_list|,
name|Date
name|timestamp
parameter_list|,
name|Set
argument_list|<
name|String
argument_list|>
name|members
parameter_list|)
block|{
name|this
operator|.
name|groupName
operator|=
name|groupName
expr_stmt|;
name|this
operator|.
name|leader
operator|=
name|leader
expr_stmt|;
name|this
operator|.
name|localTimestamp
operator|=
name|timestamp
expr_stmt|;
name|this
operator|.
name|members
operator|=
name|members
expr_stmt|;
block|}
DECL|method|hasEmptyLeader ()
specifier|public
name|boolean
name|hasEmptyLeader
parameter_list|()
block|{
return|return
name|this
operator|.
name|leader
operator|==
literal|null
return|;
block|}
DECL|method|hasValidLeader ()
specifier|public
name|boolean
name|hasValidLeader
parameter_list|()
block|{
return|return
name|this
operator|.
name|leader
operator|!=
literal|null
operator|&&
name|this
operator|.
name|members
operator|.
name|contains
argument_list|(
name|this
operator|.
name|leader
argument_list|)
return|;
block|}
DECL|method|isValidLeader (String pod)
specifier|public
name|boolean
name|isValidLeader
parameter_list|(
name|String
name|pod
parameter_list|)
block|{
name|ObjectHelper
operator|.
name|notNull
argument_list|(
name|pod
argument_list|,
literal|"pod"
argument_list|)
expr_stmt|;
return|return
name|hasValidLeader
argument_list|()
operator|&&
name|pod
operator|.
name|equals
argument_list|(
name|leader
argument_list|)
return|;
block|}
DECL|method|getGroupName ()
specifier|public
name|String
name|getGroupName
parameter_list|()
block|{
return|return
name|groupName
return|;
block|}
DECL|method|setGroupName (String groupName)
specifier|public
name|void
name|setGroupName
parameter_list|(
name|String
name|groupName
parameter_list|)
block|{
name|this
operator|.
name|groupName
operator|=
name|groupName
expr_stmt|;
block|}
DECL|method|getLeader ()
specifier|public
name|String
name|getLeader
parameter_list|()
block|{
return|return
name|leader
return|;
block|}
DECL|method|setLeader (String leader)
specifier|public
name|void
name|setLeader
parameter_list|(
name|String
name|leader
parameter_list|)
block|{
name|this
operator|.
name|leader
operator|=
name|leader
expr_stmt|;
block|}
DECL|method|getLocalTimestamp ()
specifier|public
name|Date
name|getLocalTimestamp
parameter_list|()
block|{
return|return
name|localTimestamp
return|;
block|}
DECL|method|setLocalTimestamp (Date localTimestamp)
specifier|public
name|void
name|setLocalTimestamp
parameter_list|(
name|Date
name|localTimestamp
parameter_list|)
block|{
name|this
operator|.
name|localTimestamp
operator|=
name|localTimestamp
expr_stmt|;
block|}
DECL|method|getMembers ()
specifier|public
name|Set
argument_list|<
name|String
argument_list|>
name|getMembers
parameter_list|()
block|{
return|return
name|members
return|;
block|}
DECL|method|setMembers (Set<String> members)
specifier|public
name|void
name|setMembers
parameter_list|(
name|Set
argument_list|<
name|String
argument_list|>
name|members
parameter_list|)
block|{
name|this
operator|.
name|members
operator|=
name|members
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|toString ()
specifier|public
name|String
name|toString
parameter_list|()
block|{
specifier|final
name|StringBuilder
name|sb
init|=
operator|new
name|StringBuilder
argument_list|(
literal|"LeaderInfo{"
argument_list|)
decl_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|"groupName='"
argument_list|)
operator|.
name|append
argument_list|(
name|groupName
argument_list|)
operator|.
name|append
argument_list|(
literal|'\''
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|", leader='"
argument_list|)
operator|.
name|append
argument_list|(
name|leader
argument_list|)
operator|.
name|append
argument_list|(
literal|'\''
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|", localTimestamp="
argument_list|)
operator|.
name|append
argument_list|(
name|localTimestamp
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|", members="
argument_list|)
operator|.
name|append
argument_list|(
name|members
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|'}'
argument_list|)
expr_stmt|;
return|return
name|sb
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
end_class

end_unit

