begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.dataformat.jibx.springboot
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|dataformat
operator|.
name|jibx
operator|.
name|springboot
package|;
end_package

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|boot
operator|.
name|context
operator|.
name|properties
operator|.
name|ConfigurationProperties
import|;
end_import

begin_comment
comment|/**  * Camel Jibx support  *   * Generated by camel-package-maven-plugin - do not edit this file!  */
end_comment

begin_class
annotation|@
name|ConfigurationProperties
argument_list|(
name|prefix
operator|=
literal|"camel.dataformat.jibx"
argument_list|)
DECL|class|JibxDataFormatConfiguration
specifier|public
class|class
name|JibxDataFormatConfiguration
block|{
comment|/**      * Class name to use when unmarshalling from XML to Java.      */
DECL|field|unmarshallClass
specifier|private
name|String
name|unmarshallClass
decl_stmt|;
comment|/**      * To use a custom binding factory      */
DECL|field|bindingName
specifier|private
name|String
name|bindingName
decl_stmt|;
comment|/**      * Sets the value of the id property.      */
DECL|field|id
specifier|private
name|String
name|id
decl_stmt|;
DECL|method|getUnmarshallClass ()
specifier|public
name|String
name|getUnmarshallClass
parameter_list|()
block|{
return|return
name|unmarshallClass
return|;
block|}
DECL|method|setUnmarshallClass (String unmarshallClass)
specifier|public
name|void
name|setUnmarshallClass
parameter_list|(
name|String
name|unmarshallClass
parameter_list|)
block|{
name|this
operator|.
name|unmarshallClass
operator|=
name|unmarshallClass
expr_stmt|;
block|}
DECL|method|getBindingName ()
specifier|public
name|String
name|getBindingName
parameter_list|()
block|{
return|return
name|bindingName
return|;
block|}
DECL|method|setBindingName (String bindingName)
specifier|public
name|void
name|setBindingName
parameter_list|(
name|String
name|bindingName
parameter_list|)
block|{
name|this
operator|.
name|bindingName
operator|=
name|bindingName
expr_stmt|;
block|}
DECL|method|getId ()
specifier|public
name|String
name|getId
parameter_list|()
block|{
return|return
name|id
return|;
block|}
DECL|method|setId (String id)
specifier|public
name|void
name|setId
parameter_list|(
name|String
name|id
parameter_list|)
block|{
name|this
operator|.
name|id
operator|=
name|id
expr_stmt|;
block|}
block|}
end_class

end_unit

