begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.microprofile.health
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|microprofile
operator|.
name|health
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|json
operator|.
name|JsonArray
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|json
operator|.
name|JsonObject
import|;
end_import

begin_import
import|import
name|io
operator|.
name|smallrye
operator|.
name|health
operator|.
name|SmallRyeHealth
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|ServiceStatus
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|health
operator|.
name|HealthCheckRegistry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
operator|.
name|engine
operator|.
name|ExplicitCamelContextNameStrategy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|microprofile
operator|.
name|health
operator|.
name|HealthCheckResponse
operator|.
name|State
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
DECL|class|CamelMicroProfileHealthCheckTest
specifier|public
class|class
name|CamelMicroProfileHealthCheckTest
extends|extends
name|CamelMicroProfileHealthTestSupport
block|{
annotation|@
name|Test
DECL|method|testCamelContextHealthCheckUpStatus ()
specifier|public
name|void
name|testCamelContextHealthCheckUpStatus
parameter_list|()
block|{
name|context
operator|.
name|setNameStrategy
argument_list|(
operator|new
name|ExplicitCamelContextNameStrategy
argument_list|(
literal|"health-context"
argument_list|)
argument_list|)
expr_stmt|;
name|CamelMicroProfileContextCheck
name|check
init|=
operator|new
name|CamelMicroProfileContextCheck
argument_list|()
decl_stmt|;
name|check
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|check
argument_list|)
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel"
argument_list|,
name|State
operator|.
name|UP
argument_list|,
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
argument_list|,
parameter_list|(
name|checksJson
parameter_list|)
lambda|->
block|{
name|assertEquals
argument_list|(
name|ServiceStatus
operator|.
name|Started
operator|.
name|toString
argument_list|()
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"contextStatus"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"health-context"
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"name"
argument_list|)
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCamelContextHealthCheckDownStatus ()
specifier|public
name|void
name|testCamelContextHealthCheckDownStatus
parameter_list|()
block|{
name|context
operator|.
name|setNameStrategy
argument_list|(
operator|new
name|ExplicitCamelContextNameStrategy
argument_list|(
literal|"health-context"
argument_list|)
argument_list|)
expr_stmt|;
name|CamelMicroProfileContextCheck
name|check
init|=
operator|new
name|CamelMicroProfileContextCheck
argument_list|()
decl_stmt|;
name|check
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|check
argument_list|)
expr_stmt|;
name|context
operator|.
name|stop
argument_list|()
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|DOWN
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel"
argument_list|,
name|State
operator|.
name|DOWN
argument_list|,
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
argument_list|,
parameter_list|(
name|checksJson
parameter_list|)
lambda|->
block|{
name|assertEquals
argument_list|(
name|ServiceStatus
operator|.
name|Stopped
operator|.
name|toString
argument_list|()
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"contextStatus"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"health-context"
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"name"
argument_list|)
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCamelMicroProfileLivenessCheckUpStatus ()
specifier|public
name|void
name|testCamelMicroProfileLivenessCheckUpStatus
parameter_list|()
block|{
name|HealthCheckRegistry
name|healthCheckRegistry
init|=
name|HealthCheckRegistry
operator|.
name|get
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createLivenessCheck
argument_list|(
literal|"liveness-1"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createLivenessCheck
argument_list|(
literal|"liveness-2"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createReadinessCheck
argument_list|(
literal|"readiness-3"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|CamelMicroProfileLivenessCheck
name|livenessCheck
init|=
operator|new
name|CamelMicroProfileLivenessCheck
argument_list|()
decl_stmt|;
name|livenessCheck
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|livenessCheck
argument_list|)
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|JsonObject
name|checksObject
init|=
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel-liveness-checks"
argument_list|,
name|State
operator|.
name|UP
argument_list|,
name|checksObject
argument_list|,
name|checksJson
lambda|->
block|{
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"liveness-1"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"liveness-2"
argument_list|)
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCamelMicroProfileLivenessCheckDownStatus ()
specifier|public
name|void
name|testCamelMicroProfileLivenessCheckDownStatus
parameter_list|()
block|{
name|HealthCheckRegistry
name|healthCheckRegistry
init|=
name|HealthCheckRegistry
operator|.
name|get
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createLivenessCheck
argument_list|(
literal|"liveness-1"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createLivenessCheck
argument_list|(
literal|"liveness-2"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|down
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createReadinessCheck
argument_list|(
literal|"readiness-3"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|CamelMicroProfileLivenessCheck
name|livenessCheck
init|=
operator|new
name|CamelMicroProfileLivenessCheck
argument_list|()
decl_stmt|;
name|livenessCheck
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|livenessCheck
argument_list|)
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|DOWN
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|JsonObject
name|checksObject
init|=
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel-liveness-checks"
argument_list|,
name|State
operator|.
name|DOWN
argument_list|,
name|checksObject
argument_list|,
name|checksJson
lambda|->
block|{
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"liveness-1"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|DOWN
operator|.
name|name
argument_list|()
argument_list|,
name|checksJson
operator|.
name|getString
argument_list|(
literal|"liveness-2"
argument_list|)
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCamelMicroProfileReadinessCheckUpStatus ()
specifier|public
name|void
name|testCamelMicroProfileReadinessCheckUpStatus
parameter_list|()
block|{
name|HealthCheckRegistry
name|healthCheckRegistry
init|=
name|HealthCheckRegistry
operator|.
name|get
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createLivenessCheck
argument_list|(
literal|"liveness-1"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createReadinessCheck
argument_list|(
literal|"readiness-1"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createReadinessCheck
argument_list|(
literal|"readiness-2"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|CamelMicroProfileReadinessCheck
name|readinessCheck
init|=
operator|new
name|CamelMicroProfileReadinessCheck
argument_list|()
decl_stmt|;
name|readinessCheck
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|readinessCheck
argument_list|)
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel-readiness-checks"
argument_list|,
name|State
operator|.
name|UP
argument_list|,
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
argument_list|,
name|jsonObject
lambda|->
block|{
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|jsonObject
operator|.
name|getString
argument_list|(
literal|"readiness-1"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|jsonObject
operator|.
name|getString
argument_list|(
literal|"readiness-2"
argument_list|)
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCamelMicroProfileReadinessCheckDownStatus ()
specifier|public
name|void
name|testCamelMicroProfileReadinessCheckDownStatus
parameter_list|()
block|{
name|HealthCheckRegistry
name|healthCheckRegistry
init|=
name|HealthCheckRegistry
operator|.
name|get
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createLivenessCheck
argument_list|(
literal|"liveness-1"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createReadinessCheck
argument_list|(
literal|"readiness-1"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createReadinessCheck
argument_list|(
literal|"readiness-2"
argument_list|,
literal|true
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|down
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|CamelMicroProfileReadinessCheck
name|readinessCheck
init|=
operator|new
name|CamelMicroProfileReadinessCheck
argument_list|()
decl_stmt|;
name|readinessCheck
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|readinessCheck
argument_list|)
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|DOWN
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel-readiness-checks"
argument_list|,
name|State
operator|.
name|DOWN
argument_list|,
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
argument_list|,
name|jsonObject
lambda|->
block|{
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|jsonObject
operator|.
name|getString
argument_list|(
literal|"readiness-1"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|DOWN
operator|.
name|name
argument_list|()
argument_list|,
name|jsonObject
operator|.
name|getString
argument_list|(
literal|"readiness-2"
argument_list|)
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCamelHealthCheckDisabled ()
specifier|public
name|void
name|testCamelHealthCheckDisabled
parameter_list|()
block|{
name|HealthCheckRegistry
name|healthCheckRegistry
init|=
name|HealthCheckRegistry
operator|.
name|get
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|healthCheckRegistry
operator|.
name|register
argument_list|(
name|createReadinessCheck
argument_list|(
literal|"disabled-check"
argument_list|,
literal|false
argument_list|,
name|builder
lambda|->
name|builder
operator|.
name|up
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|CamelMicroProfileReadinessCheck
name|readinessCheck
init|=
operator|new
name|CamelMicroProfileReadinessCheck
argument_list|()
decl_stmt|;
name|readinessCheck
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|readinessCheck
argument_list|)
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|UP
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel-readiness-checks"
argument_list|,
name|State
operator|.
name|UP
argument_list|,
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
argument_list|,
name|jsonObject
lambda|->
block|{
name|assertNull
argument_list|(
name|jsonObject
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testNoCamelHealthChecksRegistered ()
specifier|public
name|void
name|testNoCamelHealthChecksRegistered
parameter_list|()
block|{
name|CamelMicroProfileReadinessCheck
name|readinessCheck
init|=
operator|new
name|CamelMicroProfileReadinessCheck
argument_list|()
decl_stmt|;
name|readinessCheck
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|readinessCheck
argument_list|)
expr_stmt|;
name|CamelMicroProfileLivenessCheck
name|livenessCheck
init|=
operator|new
name|CamelMicroProfileLivenessCheck
argument_list|()
decl_stmt|;
name|livenessCheck
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|reporter
operator|.
name|addHealthCheck
argument_list|(
name|livenessCheck
argument_list|)
expr_stmt|;
name|SmallRyeHealth
name|health
init|=
name|reporter
operator|.
name|getHealth
argument_list|()
decl_stmt|;
name|JsonObject
name|healthObject
init|=
name|getHealthJson
argument_list|(
name|health
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|State
operator|.
name|DOWN
operator|.
name|name
argument_list|()
argument_list|,
name|healthObject
operator|.
name|getString
argument_list|(
literal|"status"
argument_list|)
argument_list|)
expr_stmt|;
name|JsonArray
name|checks
init|=
name|healthObject
operator|.
name|getJsonArray
argument_list|(
literal|"checks"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|checks
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel-readiness-checks"
argument_list|,
name|State
operator|.
name|DOWN
argument_list|,
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|0
argument_list|)
argument_list|,
name|jsonObject
lambda|->
block|{
name|assertNull
argument_list|(
name|jsonObject
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
name|assertHealthCheckOutput
argument_list|(
literal|"camel-liveness-checks"
argument_list|,
name|State
operator|.
name|DOWN
argument_list|,
name|checks
operator|.
name|getJsonObject
argument_list|(
literal|1
argument_list|)
argument_list|,
name|jsonObject
lambda|->
block|{
name|assertNull
argument_list|(
name|jsonObject
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

