begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.jetty
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|jetty
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|net
operator|.
name|ssl
operator|.
name|SSLContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|RuntimeCamelException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|util
operator|.
name|ObjectHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|client
operator|.
name|HttpClient
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|util
operator|.
name|thread
operator|.
name|QueuedThreadPool
import|;
end_import

begin_class
DECL|class|CamelHttpClient
specifier|public
class|class
name|CamelHttpClient
extends|extends
name|HttpClient
block|{
DECL|field|context
specifier|private
name|SSLContext
name|context
decl_stmt|;
annotation|@
name|Override
DECL|method|getSSLContext ()
specifier|protected
name|SSLContext
name|getSSLContext
parameter_list|()
block|{
if|if
condition|(
name|context
operator|==
literal|null
condition|)
block|{
name|this
operator|.
name|context
operator|=
name|super
operator|.
name|getSSLContext
argument_list|()
expr_stmt|;
block|}
return|return
name|this
operator|.
name|context
return|;
block|}
DECL|method|setSSLContext (SSLContext context)
specifier|public
name|void
name|setSSLContext
parameter_list|(
name|SSLContext
name|context
parameter_list|)
block|{
name|this
operator|.
name|context
operator|=
name|context
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|doStart ()
specifier|protected
name|void
name|doStart
parameter_list|()
throws|throws
name|Exception
block|{
if|if
condition|(
name|getThreadPool
argument_list|()
operator|==
literal|null
condition|)
block|{
comment|// if there is no thread pool then create a default thread pool using daemon threads
name|QueuedThreadPool
name|qtp
init|=
operator|new
name|QueuedThreadPool
argument_list|()
decl_stmt|;
comment|// 16 max threads is the default in the http client
name|qtp
operator|.
name|setMaxThreads
argument_list|(
literal|16
argument_list|)
expr_stmt|;
name|qtp
operator|.
name|setDaemon
argument_list|(
literal|true
argument_list|)
expr_stmt|;
comment|// let the thread names indicate they are from the client
name|qtp
operator|.
name|setName
argument_list|(
literal|"CamelJettyClient("
operator|+
name|ObjectHelper
operator|.
name|getIdentityHashCode
argument_list|(
name|this
argument_list|)
operator|+
literal|")"
argument_list|)
expr_stmt|;
name|setThreadPool
argument_list|(
name|qtp
argument_list|)
expr_stmt|;
block|}
name|super
operator|.
name|doStart
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

