begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.spring.spi
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|spring
operator|.
name|spi
package|;
end_package

begin_import
import|import
name|java
operator|.
name|lang
operator|.
name|reflect
operator|.
name|Method
import|;
end_import

begin_import
import|import
name|java
operator|.
name|lang
operator|.
name|reflect
operator|.
name|Modifier
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|RuntimeCamelException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|spi
operator|.
name|Injector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|beans
operator|.
name|factory
operator|.
name|config
operator|.
name|AutowireCapableBeanFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|context
operator|.
name|ConfigurableApplicationContext
import|;
end_import

begin_comment
comment|/**  * A Spring implementation of {@link Injector} allowing Spring to be used to dependency inject newly created POJOs  */
end_comment

begin_class
DECL|class|SpringInjector
specifier|public
class|class
name|SpringInjector
implements|implements
name|Injector
block|{
DECL|field|applicationContext
specifier|private
specifier|final
name|ConfigurableApplicationContext
name|applicationContext
decl_stmt|;
DECL|field|autowireMode
specifier|private
name|int
name|autowireMode
init|=
name|AutowireCapableBeanFactory
operator|.
name|AUTOWIRE_CONSTRUCTOR
decl_stmt|;
DECL|field|dependencyCheck
specifier|private
name|boolean
name|dependencyCheck
decl_stmt|;
DECL|method|SpringInjector (ConfigurableApplicationContext applicationContext)
specifier|public
name|SpringInjector
parameter_list|(
name|ConfigurableApplicationContext
name|applicationContext
parameter_list|)
block|{
name|this
operator|.
name|applicationContext
operator|=
name|applicationContext
expr_stmt|;
block|}
DECL|method|newInstance (Class<T> type)
specifier|public
parameter_list|<
name|T
parameter_list|>
name|T
name|newInstance
parameter_list|(
name|Class
argument_list|<
name|T
argument_list|>
name|type
parameter_list|)
block|{
return|return
name|newInstance
argument_list|(
name|type
argument_list|,
literal|true
argument_list|)
return|;
block|}
annotation|@
name|Override
DECL|method|newInstance (Class<T> type, String factoryMethod)
specifier|public
parameter_list|<
name|T
parameter_list|>
name|T
name|newInstance
parameter_list|(
name|Class
argument_list|<
name|T
argument_list|>
name|type
parameter_list|,
name|String
name|factoryMethod
parameter_list|)
block|{
name|T
name|answer
init|=
literal|null
decl_stmt|;
try|try
block|{
comment|// lookup factory method
name|Method
name|fm
init|=
name|type
operator|.
name|getMethod
argument_list|(
name|factoryMethod
argument_list|)
decl_stmt|;
if|if
condition|(
name|Modifier
operator|.
name|isStatic
argument_list|(
name|fm
operator|.
name|getModifiers
argument_list|()
argument_list|)
operator|&&
name|Modifier
operator|.
name|isPublic
argument_list|(
name|fm
operator|.
name|getModifiers
argument_list|()
argument_list|)
operator|&&
name|fm
operator|.
name|getReturnType
argument_list|()
operator|==
name|type
condition|)
block|{
name|Object
name|obj
init|=
name|fm
operator|.
name|invoke
argument_list|(
literal|null
argument_list|)
decl_stmt|;
name|answer
operator|=
name|type
operator|.
name|cast
argument_list|(
name|obj
argument_list|)
expr_stmt|;
block|}
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|RuntimeCamelException
argument_list|(
literal|"Error invoking factory method: "
operator|+
name|factoryMethod
operator|+
literal|" on class: "
operator|+
name|type
argument_list|,
name|e
argument_list|)
throw|;
block|}
return|return
name|answer
return|;
block|}
annotation|@
name|Override
DECL|method|newInstance (Class<T> type, boolean postProcessBean)
specifier|public
parameter_list|<
name|T
parameter_list|>
name|T
name|newInstance
parameter_list|(
name|Class
argument_list|<
name|T
argument_list|>
name|type
parameter_list|,
name|boolean
name|postProcessBean
parameter_list|)
block|{
name|Object
name|value
decl_stmt|;
if|if
condition|(
name|postProcessBean
condition|)
block|{
name|value
operator|=
name|applicationContext
operator|.
name|getBeanFactory
argument_list|()
operator|.
name|createBean
argument_list|(
name|type
argument_list|,
name|autowireMode
argument_list|,
name|dependencyCheck
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|value
operator|=
name|applicationContext
operator|.
name|getBeanFactory
argument_list|()
operator|.
name|createBean
argument_list|(
name|type
argument_list|,
name|AutowireCapableBeanFactory
operator|.
name|AUTOWIRE_NO
argument_list|,
literal|false
argument_list|)
expr_stmt|;
block|}
return|return
name|type
operator|.
name|cast
argument_list|(
name|value
argument_list|)
return|;
block|}
annotation|@
name|Override
DECL|method|supportsAutoWiring ()
specifier|public
name|boolean
name|supportsAutoWiring
parameter_list|()
block|{
return|return
literal|true
return|;
block|}
DECL|method|getAutowireMode ()
specifier|public
name|int
name|getAutowireMode
parameter_list|()
block|{
return|return
name|autowireMode
return|;
block|}
DECL|method|setAutowireMode (int autowireMode)
specifier|public
name|void
name|setAutowireMode
parameter_list|(
name|int
name|autowireMode
parameter_list|)
block|{
name|this
operator|.
name|autowireMode
operator|=
name|autowireMode
expr_stmt|;
block|}
DECL|method|isDependencyCheck ()
specifier|public
name|boolean
name|isDependencyCheck
parameter_list|()
block|{
return|return
name|dependencyCheck
return|;
block|}
DECL|method|setDependencyCheck (boolean dependencyCheck)
specifier|public
name|void
name|setDependencyCheck
parameter_list|(
name|boolean
name|dependencyCheck
parameter_list|)
block|{
name|this
operator|.
name|dependencyCheck
operator|=
name|dependencyCheck
expr_stmt|;
block|}
DECL|method|getApplicationContext ()
specifier|public
name|ConfigurableApplicationContext
name|getApplicationContext
parameter_list|()
block|{
return|return
name|applicationContext
return|;
block|}
block|}
end_class

end_unit

