begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  *  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.management
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|management
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|management
operator|.
name|MBeanServer
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|management
operator|.
name|ObjectName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|CamelContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|ContextTestSupport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|builder
operator|.
name|RouteBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|mock
operator|.
name|MockEndpoint
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|management
operator|.
name|InstrumentationAgentImpl
import|;
end_import

begin_class
DECL|class|JmxInstrumentationUsingDefaultsTest
specifier|public
class|class
name|JmxInstrumentationUsingDefaultsTest
extends|extends
name|ContextTestSupport
block|{
DECL|field|DEFAULT_PORT
specifier|public
specifier|static
specifier|final
name|int
name|DEFAULT_PORT
init|=
literal|1099
decl_stmt|;
DECL|field|iAgent
specifier|protected
name|InstrumentationAgentImpl
name|iAgent
decl_stmt|;
DECL|field|domainName
specifier|protected
name|String
name|domainName
init|=
name|InstrumentationAgentImpl
operator|.
name|DEFAULT_DOMAIN
decl_stmt|;
DECL|field|sleepSoYouCanBrowseInJConsole
specifier|protected
name|boolean
name|sleepSoYouCanBrowseInJConsole
init|=
literal|false
decl_stmt|;
DECL|method|testMBeansRegistered ()
specifier|public
name|void
name|testMBeansRegistered
parameter_list|()
throws|throws
name|Exception
block|{
name|assertNotNull
argument_list|(
name|iAgent
operator|.
name|getMBeanServer
argument_list|()
argument_list|)
expr_stmt|;
comment|//assertEquals(domainName, iAgent.getMBeanServer().getDefaultDomain());
name|resolveMandatoryEndpoint
argument_list|(
literal|"mock:end"
argument_list|,
name|MockEndpoint
operator|.
name|class
argument_list|)
expr_stmt|;
name|ObjectName
name|name
init|=
operator|new
name|ObjectName
argument_list|(
name|domainName
operator|+
literal|":group=endpoints,*"
argument_list|)
decl_stmt|;
name|Set
name|s
init|=
name|iAgent
operator|.
name|getMBeanServer
argument_list|()
operator|.
name|queryNames
argument_list|(
name|name
argument_list|,
literal|null
argument_list|)
decl_stmt|;
if|if
condition|(
name|sleepSoYouCanBrowseInJConsole
condition|)
block|{
name|Thread
operator|.
name|sleep
argument_list|(
literal|100000
argument_list|)
expr_stmt|;
block|}
name|assertEquals
argument_list|(
literal|"Could not find 2 endpoints: "
operator|+
name|s
argument_list|,
literal|2
argument_list|,
name|s
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|method|testCounters ()
specifier|public
name|void
name|testCounters
parameter_list|()
throws|throws
name|Exception
block|{
name|MockEndpoint
name|resultEndpoint
init|=
name|resolveMandatoryEndpoint
argument_list|(
literal|"mock:end"
argument_list|,
name|MockEndpoint
operator|.
name|class
argument_list|)
decl_stmt|;
name|resultEndpoint
operator|.
name|expectedBodiesReceived
argument_list|(
literal|"<hello>world!</hello>"
argument_list|)
expr_stmt|;
name|sendBody
argument_list|(
literal|"direct:start"
argument_list|,
literal|"<hello>world!</hello>"
argument_list|)
expr_stmt|;
name|resultEndpoint
operator|.
name|assertIsSatisfied
argument_list|()
expr_stmt|;
comment|/*           * Fixme: after stats are merged with the mbean they represent          *          MBeanServer mbs = iAgent.getMBeanServer();         ObjectName name = new ObjectName(domainName + ":name=Stats,*");         Set s = mbs.queryNames(name, null);         assertEquals("Found mbeans: " + s, 1, s.size());          Iterator iter = s.iterator();         ObjectName pcob = (ObjectName)iter.next();          Long valueofNumExchanges = (Long)mbs.getAttribute(pcob, "NumExchanges");         assertNotNull("Expected attribute not found. MBean registerred under a " +         		"'<domain>:name=Stats,*' key must be of type PerformanceCounter.class", valueofNumExchanges);         assertTrue(valueofNumExchanges == 1);         Long valueofNumCompleted = (Long)mbs.getAttribute(pcob, "NumCompleted");         assertNotNull("Expected attribute not found. MBean registerred under a " +         		"'<domain>:name=Stats,*' key must be of type PerformanceCounter.class", valueofNumCompleted);         assertTrue(valueofNumCompleted == 1);         Long valueofNumFailed = (Long)mbs.getAttribute(pcob, "NumFailed");         assertNotNull("Expected attribute not found. MBean registerred under a " +         		"'<domain>:name=Stats,*' key must be of type PerformanceCounter.class", valueofNumFailed);         assertTrue(valueofNumFailed == 0);         Long valueofMinProcessingTime = (Long)mbs.getAttribute(pcob, "MinProcessingTime");         assertNotNull("Expected attribute not found. MBean registerred under a " +         		"'<domain>:name=Stats,*' key must be of type PerformanceCounter.class", valueofMinProcessingTime);         assertTrue(valueofMinProcessingTime> 0);         Long valueofMaxProcessingTime = (Long)mbs.getAttribute(pcob, "MaxProcessingTime");         assertNotNull("Expected attribute not found. MBean registerred under a " +         		"'<domain>:name=Stats,*' key must be of type PerformanceCounter.class", valueofMaxProcessingTime);         assertTrue(valueofMaxProcessingTime> 0);         Long valueofMeanProcessingTime = (Long)mbs.getAttribute(pcob, "MeanProcessingTime");         assertNotNull("Expected attribute not found. MBean registerred under a " +         		"'<domain>:name=Stats,*' key must be of type PerformanceCounter.class", valueofMeanProcessingTime);         assertTrue(valueofMeanProcessingTime>= valueofMinProcessingTime&&         		valueofMeanProcessingTime<= valueofMaxProcessingTime);          */
block|}
DECL|method|enableJmx ()
specifier|protected
name|void
name|enableJmx
parameter_list|()
block|{
name|iAgent
operator|.
name|enableJmx
argument_list|(
literal|null
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
DECL|method|createCamelContext ()
specifier|protected
name|CamelContext
name|createCamelContext
parameter_list|()
throws|throws
name|Exception
block|{
name|CamelContext
name|context
init|=
name|super
operator|.
name|createCamelContext
argument_list|()
decl_stmt|;
name|createInstrumentationAgent
argument_list|(
name|context
argument_list|,
name|DEFAULT_PORT
argument_list|)
expr_stmt|;
return|return
name|context
return|;
block|}
DECL|method|createInstrumentationAgent (CamelContext context, int port)
specifier|protected
name|void
name|createInstrumentationAgent
parameter_list|(
name|CamelContext
name|context
parameter_list|,
name|int
name|port
parameter_list|)
throws|throws
name|Exception
block|{
name|iAgent
operator|=
operator|new
name|InstrumentationAgentImpl
argument_list|()
expr_stmt|;
name|iAgent
operator|.
name|setCamelContext
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|enableJmx
argument_list|()
expr_stmt|;
name|iAgent
operator|.
name|start
argument_list|()
expr_stmt|;
block|}
DECL|method|createRouteBuilder ()
specifier|protected
name|RouteBuilder
name|createRouteBuilder
parameter_list|()
block|{
return|return
operator|new
name|RouteBuilder
argument_list|()
block|{
specifier|public
name|void
name|configure
parameter_list|()
block|{
name|from
argument_list|(
literal|"direct:start"
argument_list|)
operator|.
name|to
argument_list|(
literal|"mock:end"
argument_list|)
expr_stmt|;
block|}
block|}
return|;
block|}
annotation|@
name|Override
DECL|method|tearDown ()
specifier|protected
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|iAgent
operator|.
name|stop
argument_list|()
expr_stmt|;
name|super
operator|.
name|tearDown
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

