begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.impl.converter
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
operator|.
name|converter
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Converter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|TypeConverters
import|;
end_import

begin_class
DECL|class|MyConverters
specifier|public
class|class
name|MyConverters
implements|implements
name|TypeConverters
block|{
annotation|@
name|Converter
DECL|method|toCountry (String iso)
specifier|public
name|Country
name|toCountry
parameter_list|(
name|String
name|iso
parameter_list|)
block|{
name|Country
name|answer
init|=
operator|new
name|Country
argument_list|()
decl_stmt|;
name|answer
operator|.
name|setIso
argument_list|(
literal|"en"
argument_list|)
expr_stmt|;
name|answer
operator|.
name|setName
argument_list|(
literal|"England"
argument_list|)
expr_stmt|;
return|return
name|answer
return|;
block|}
annotation|@
name|Converter
DECL|method|toIso (Country country)
specifier|public
name|String
name|toIso
parameter_list|(
name|Country
name|country
parameter_list|)
block|{
return|return
name|country
operator|.
name|getIso
argument_list|()
return|;
block|}
block|}
end_class

end_unit

