begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.mongodb3
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|mongodb3
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|ExecutorService
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|util
operator|.
name|Collections
operator|.
name|singletonList
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Processor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|support
operator|.
name|DefaultConsumer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|util
operator|.
name|ObjectHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|bson
operator|.
name|BsonDocument
import|;
end_import

begin_comment
comment|/**  * The MongoDb Change Streams consumer.  */
end_comment

begin_class
DECL|class|MongoDbChangeStreamsConsumer
specifier|public
class|class
name|MongoDbChangeStreamsConsumer
extends|extends
name|DefaultConsumer
block|{
DECL|field|STREAM_FILTER_PROPERTY
specifier|private
specifier|static
specifier|final
name|String
name|STREAM_FILTER_PROPERTY
init|=
literal|"streamFilter"
decl_stmt|;
DECL|field|endpoint
specifier|private
specifier|final
name|MongoDbEndpoint
name|endpoint
decl_stmt|;
DECL|field|executor
specifier|private
name|ExecutorService
name|executor
decl_stmt|;
DECL|field|changeStreamsThread
specifier|private
name|MongoDbChangeStreamsThread
name|changeStreamsThread
decl_stmt|;
DECL|method|MongoDbChangeStreamsConsumer (MongoDbEndpoint endpoint, Processor processor)
specifier|public
name|MongoDbChangeStreamsConsumer
parameter_list|(
name|MongoDbEndpoint
name|endpoint
parameter_list|,
name|Processor
name|processor
parameter_list|)
block|{
name|super
argument_list|(
name|endpoint
argument_list|,
name|processor
argument_list|)
expr_stmt|;
name|this
operator|.
name|endpoint
operator|=
name|endpoint
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|doStop ()
specifier|protected
name|void
name|doStop
parameter_list|()
throws|throws
name|Exception
block|{
name|super
operator|.
name|doStop
argument_list|()
expr_stmt|;
if|if
condition|(
name|changeStreamsThread
operator|!=
literal|null
condition|)
block|{
name|changeStreamsThread
operator|.
name|stop
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|executor
operator|!=
literal|null
condition|)
block|{
name|endpoint
operator|.
name|getCamelContext
argument_list|()
operator|.
name|getExecutorServiceManager
argument_list|()
operator|.
name|shutdown
argument_list|(
name|executor
argument_list|)
expr_stmt|;
name|executor
operator|=
literal|null
expr_stmt|;
block|}
block|}
annotation|@
name|Override
DECL|method|doStart ()
specifier|protected
name|void
name|doStart
parameter_list|()
throws|throws
name|Exception
block|{
name|super
operator|.
name|doStart
argument_list|()
expr_stmt|;
name|String
name|streamFilter
init|=
operator|(
name|String
operator|)
name|getRoute
argument_list|()
operator|.
name|getProperties
argument_list|()
operator|.
name|get
argument_list|(
name|STREAM_FILTER_PROPERTY
argument_list|)
decl_stmt|;
name|List
argument_list|<
name|BsonDocument
argument_list|>
name|bsonFilter
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|ObjectHelper
operator|.
name|isNotEmpty
argument_list|(
name|streamFilter
argument_list|)
condition|)
block|{
name|bsonFilter
operator|=
name|singletonList
argument_list|(
name|BsonDocument
operator|.
name|parse
argument_list|(
name|streamFilter
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|executor
operator|=
name|endpoint
operator|.
name|getCamelContext
argument_list|()
operator|.
name|getExecutorServiceManager
argument_list|()
operator|.
name|newFixedThreadPool
argument_list|(
name|this
argument_list|,
name|endpoint
operator|.
name|getEndpointUri
argument_list|()
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|changeStreamsThread
operator|=
operator|new
name|MongoDbChangeStreamsThread
argument_list|(
name|endpoint
argument_list|,
name|this
argument_list|,
name|bsonFilter
argument_list|)
expr_stmt|;
name|changeStreamsThread
operator|.
name|init
argument_list|()
expr_stmt|;
name|executor
operator|.
name|execute
argument_list|(
name|changeStreamsThread
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

