begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.converter.soap.name
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|converter
operator|.
name|soap
operator|.
name|name
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_import
import|import
name|com
operator|.
name|example
operator|.
name|customerservice
operator|.
name|GetCustomersByName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|dataformat
operator|.
name|soap
operator|.
name|name
operator|.
name|TypeNameStrategy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
DECL|class|TypeNameStrategyTest
specifier|public
class|class
name|TypeNameStrategyTest
block|{
annotation|@
name|Test
DECL|method|testTypeNameStrategy ()
specifier|public
name|void
name|testTypeNameStrategy
parameter_list|()
block|{
name|TypeNameStrategy
name|strategy
init|=
operator|new
name|TypeNameStrategy
argument_list|()
decl_stmt|;
name|QName
name|name
init|=
name|strategy
operator|.
name|findQNameForSoapActionOrType
argument_list|(
literal|""
argument_list|,
name|GetCustomersByName
operator|.
name|class
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"http://customerservice.example.com/"
argument_list|,
name|name
operator|.
name|getNamespaceURI
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"getCustomersByName"
argument_list|,
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testNoAnnotation ()
specifier|public
name|void
name|testNoAnnotation
parameter_list|()
block|{
name|TypeNameStrategy
name|strategy
init|=
operator|new
name|TypeNameStrategy
argument_list|()
decl_stmt|;
try|try
block|{
name|strategy
operator|.
name|findQNameForSoapActionOrType
argument_list|(
literal|""
argument_list|,
name|String
operator|.
name|class
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|fail
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|RuntimeException
name|e
parameter_list|)
block|{
comment|// Expected here
block|}
block|}
annotation|@
name|Test
DECL|method|testNoPackageInfo ()
specifier|public
name|void
name|testNoPackageInfo
parameter_list|()
block|{
name|TypeNameStrategy
name|strategy
init|=
operator|new
name|TypeNameStrategy
argument_list|()
decl_stmt|;
name|QName
name|name
init|=
name|strategy
operator|.
name|findQNameForSoapActionOrType
argument_list|(
literal|""
argument_list|,
name|AnnotatedClassWithoutNamespace
operator|.
name|class
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"test"
argument_list|,
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"##default"
argument_list|,
name|name
operator|.
name|getNamespaceURI
argument_list|()
argument_list|)
expr_stmt|;
name|QName
name|name2
init|=
name|strategy
operator|.
name|findQNameForSoapActionOrType
argument_list|(
literal|""
argument_list|,
name|AnnotatedClassWithNamespace
operator|.
name|class
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"test"
argument_list|,
name|name2
operator|.
name|getLocalPart
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"http://mynamespace"
argument_list|,
name|name2
operator|.
name|getNamespaceURI
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

