begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.generator.swagger
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|generator
operator|.
name|swagger
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|processing
operator|.
name|Filer
import|;
end_import

begin_import
import|import
name|com
operator|.
name|squareup
operator|.
name|javapoet
operator|.
name|JavaFile
import|;
end_import

begin_import
import|import
name|io
operator|.
name|swagger
operator|.
name|models
operator|.
name|Swagger
import|;
end_import

begin_class
DECL|class|FilerGenerator
specifier|final
class|class
name|FilerGenerator
extends|extends
name|RestDslSourceCodeGenerator
argument_list|<
name|Filer
argument_list|>
block|{
DECL|method|FilerGenerator (final Swagger swagger)
name|FilerGenerator
parameter_list|(
specifier|final
name|Swagger
name|swagger
parameter_list|)
block|{
name|super
argument_list|(
name|swagger
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|generate (final Filer destination)
specifier|public
name|void
name|generate
parameter_list|(
specifier|final
name|Filer
name|destination
parameter_list|)
throws|throws
name|IOException
block|{
specifier|final
name|JavaFile
name|javaFile
init|=
name|generateSourceCode
argument_list|()
decl_stmt|;
name|javaFile
operator|.
name|writeTo
argument_list|(
name|destination
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

