begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.jaxb
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|jaxb
package|;
end_package

begin_import
import|import
name|com
operator|.
name|sun
operator|.
name|xml
operator|.
name|bind
operator|.
name|marshaller
operator|.
name|NamespacePrefixMapper
import|;
end_import

begin_class
DECL|class|MyNameSpacePrefixMapper
specifier|public
class|class
name|MyNameSpacePrefixMapper
extends|extends
name|NamespacePrefixMapper
block|{
annotation|@
name|Override
DECL|method|getPreferredPrefix (String namespaceUri, String suggestion, boolean requirePrefix)
specifier|public
name|String
name|getPreferredPrefix
parameter_list|(
name|String
name|namespaceUri
parameter_list|,
name|String
name|suggestion
parameter_list|,
name|boolean
name|requirePrefix
parameter_list|)
block|{
if|if
condition|(
name|namespaceUri
operator|.
name|equals
argument_list|(
literal|"http://www.camel.apache.org/jaxb/example/order/1"
argument_list|)
condition|)
block|{
return|return
literal|"order"
return|;
block|}
elseif|else
if|if
condition|(
name|namespaceUri
operator|.
name|equals
argument_list|(
literal|"http://www.camel.apache.org/jaxb/example/address/1"
argument_list|)
condition|)
block|{
return|return
literal|"address"
return|;
block|}
return|return
literal|"ns"
return|;
block|}
block|}
end_class

end_unit

