begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.as2.api
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|as2
operator|.
name|api
package|;
end_package

begin_import
import|import
name|org
operator|.
name|bouncycastle
operator|.
name|asn1
operator|.
name|ASN1ObjectIdentifier
import|;
end_import

begin_import
import|import
name|org
operator|.
name|bouncycastle
operator|.
name|cms
operator|.
name|jcajce
operator|.
name|ZlibCompressor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|bouncycastle
operator|.
name|operator
operator|.
name|OutputCompressor
import|;
end_import

begin_enum
DECL|enum|AS2CompressionAlgorithm
specifier|public
enum|enum
name|AS2CompressionAlgorithm
block|{
DECL|enumConstant|ZLIB
name|ZLIB
argument_list|(
operator|new
name|ZlibCompressor
argument_list|()
argument_list|)
block|;
DECL|field|outputCompressor
specifier|private
name|OutputCompressor
name|outputCompressor
decl_stmt|;
DECL|method|AS2CompressionAlgorithm (OutputCompressor outputCompressor)
specifier|private
name|AS2CompressionAlgorithm
parameter_list|(
name|OutputCompressor
name|outputCompressor
parameter_list|)
block|{
name|this
operator|.
name|outputCompressor
operator|=
name|outputCompressor
expr_stmt|;
block|}
DECL|method|getAlgorithmName ()
specifier|public
name|String
name|getAlgorithmName
parameter_list|()
block|{
return|return
name|this
operator|.
name|name
argument_list|()
return|;
block|}
DECL|method|getAlgorithmOID ()
specifier|public
name|ASN1ObjectIdentifier
name|getAlgorithmOID
parameter_list|()
block|{
return|return
name|outputCompressor
operator|.
name|getAlgorithmIdentifier
argument_list|()
operator|.
name|getAlgorithm
argument_list|()
return|;
block|}
DECL|method|getOutputCompressor ()
specifier|public
name|OutputCompressor
name|getOutputCompressor
parameter_list|()
block|{
return|return
name|outputCompressor
return|;
block|}
block|}
end_enum

end_unit

