begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  *  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.processor
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|processor
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Endpoint
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Exchange
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Processor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|Producer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|impl
operator|.
name|ServiceSupport
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_comment
comment|/**  * Implements the Multicast pattern to send a message exchange to a number of endpoints, each endpoint receiving a copy of  * the message exchange.  *  * @version $Revision$  */
end_comment

begin_class
DECL|class|MulticastProcessor
specifier|public
class|class
name|MulticastProcessor
parameter_list|<
name|E
extends|extends
name|Exchange
parameter_list|>
extends|extends
name|ServiceSupport
implements|implements
name|Processor
argument_list|<
name|E
argument_list|>
block|{
DECL|field|producers
specifier|private
name|Collection
argument_list|<
name|Producer
argument_list|<
name|E
argument_list|>
argument_list|>
name|producers
decl_stmt|;
comment|/**      * A helper method to convert a list of endpoints into a list of processors      */
DECL|method|toProducers (Collection<Endpoint<E>> endpoints)
specifier|public
specifier|static
parameter_list|<
name|E
extends|extends
name|Exchange
parameter_list|>
name|Collection
argument_list|<
name|Producer
argument_list|<
name|E
argument_list|>
argument_list|>
name|toProducers
parameter_list|(
name|Collection
argument_list|<
name|Endpoint
argument_list|<
name|E
argument_list|>
argument_list|>
name|endpoints
parameter_list|)
throws|throws
name|Exception
block|{
name|Collection
argument_list|<
name|Producer
argument_list|<
name|E
argument_list|>
argument_list|>
name|answer
init|=
operator|new
name|ArrayList
argument_list|<
name|Producer
argument_list|<
name|E
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|Endpoint
argument_list|<
name|E
argument_list|>
name|endpoint
range|:
name|endpoints
control|)
block|{
name|answer
operator|.
name|add
argument_list|(
name|endpoint
operator|.
name|createProducer
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|answer
return|;
block|}
DECL|method|MulticastProcessor (Collection<Endpoint<E>> endpoints)
specifier|public
name|MulticastProcessor
parameter_list|(
name|Collection
argument_list|<
name|Endpoint
argument_list|<
name|E
argument_list|>
argument_list|>
name|endpoints
parameter_list|)
throws|throws
name|Exception
block|{
name|this
operator|.
name|producers
operator|=
name|toProducers
argument_list|(
name|endpoints
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|toString ()
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"Multicast"
operator|+
name|getEndpoints
argument_list|()
return|;
block|}
DECL|method|process (E exchange)
specifier|public
name|void
name|process
parameter_list|(
name|E
name|exchange
parameter_list|)
throws|throws
name|Exception
block|{
for|for
control|(
name|Producer
argument_list|<
name|E
argument_list|>
name|producer
range|:
name|producers
control|)
block|{
name|E
name|copy
init|=
name|copyExchangeStrategy
argument_list|(
name|producer
argument_list|,
name|exchange
argument_list|)
decl_stmt|;
name|producer
operator|.
name|process
argument_list|(
name|copy
argument_list|)
expr_stmt|;
block|}
block|}
DECL|method|doStop ()
specifier|protected
name|void
name|doStop
parameter_list|()
throws|throws
name|Exception
block|{
for|for
control|(
name|Producer
argument_list|<
name|E
argument_list|>
name|producer
range|:
name|producers
control|)
block|{
name|producer
operator|.
name|stop
argument_list|()
expr_stmt|;
block|}
block|}
DECL|method|doStart ()
specifier|protected
name|void
name|doStart
parameter_list|()
throws|throws
name|Exception
block|{
for|for
control|(
name|Producer
argument_list|<
name|E
argument_list|>
name|producer
range|:
name|producers
control|)
block|{
name|producer
operator|.
name|start
argument_list|()
expr_stmt|;
block|}
block|}
comment|/**      * Returns the producers to multicast to      */
DECL|method|getProducers ()
specifier|public
name|Collection
argument_list|<
name|Producer
argument_list|<
name|E
argument_list|>
argument_list|>
name|getProducers
parameter_list|()
block|{
return|return
name|producers
return|;
block|}
comment|/**      * Returns the list of endpoints      */
DECL|method|getEndpoints ()
specifier|public
name|Collection
argument_list|<
name|Endpoint
argument_list|<
name|E
argument_list|>
argument_list|>
name|getEndpoints
parameter_list|()
block|{
name|Collection
argument_list|<
name|Endpoint
argument_list|<
name|E
argument_list|>
argument_list|>
name|answer
init|=
operator|new
name|ArrayList
argument_list|<
name|Endpoint
argument_list|<
name|E
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|Producer
argument_list|<
name|E
argument_list|>
name|producer
range|:
name|producers
control|)
block|{
name|answer
operator|.
name|add
argument_list|(
name|producer
operator|.
name|getEndpoint
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|answer
return|;
block|}
comment|/**      * Strategy method to copy the exchange before sending to another endpoint. Derived classes such as the      * {@link Pipeline} will not clone the exchange      *      * @param producer the producer that will send the exchange      * @param exchange @return the current exchange if no copying is required such as for a pipeline otherwise a new copy of the exchange is returned.      */
DECL|method|copyExchangeStrategy (Producer<E> producer, E exchange)
specifier|protected
name|E
name|copyExchangeStrategy
parameter_list|(
name|Producer
argument_list|<
name|E
argument_list|>
name|producer
parameter_list|,
name|E
name|exchange
parameter_list|)
block|{
return|return
name|producer
operator|.
name|createExchange
argument_list|(
name|exchange
argument_list|)
return|;
block|}
block|}
end_class

end_unit

