begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.websocket.jsr356
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|websocket
operator|.
name|jsr356
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|util
operator|.
name|Optional
operator|.
name|ofNullable
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|servlet
operator|.
name|ServletContainerInitializer
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|servlet
operator|.
name|ServletContext
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|servlet
operator|.
name|ServletContextEvent
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|servlet
operator|.
name|ServletContextListener
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|websocket
operator|.
name|server
operator|.
name|ServerContainer
import|;
end_import

begin_class
DECL|class|ServletIntegration
specifier|public
class|class
name|ServletIntegration
implements|implements
name|ServletContainerInitializer
block|{
annotation|@
name|Override
DECL|method|onStartup (final Set<Class<?>> c, final ServletContext ctx)
specifier|public
name|void
name|onStartup
parameter_list|(
specifier|final
name|Set
argument_list|<
name|Class
argument_list|<
name|?
argument_list|>
argument_list|>
name|c
parameter_list|,
specifier|final
name|ServletContext
name|ctx
parameter_list|)
block|{
name|ctx
operator|.
name|addListener
argument_list|(
operator|new
name|ServletContextListener
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|contextInitialized
parameter_list|(
specifier|final
name|ServletContextEvent
name|sce
parameter_list|)
block|{
specifier|final
name|String
name|contextPath
init|=
name|sce
operator|.
name|getServletContext
argument_list|()
operator|.
name|getContextPath
argument_list|()
decl_stmt|;
name|ofNullable
argument_list|(
name|sce
operator|.
name|getServletContext
argument_list|()
operator|.
name|getAttribute
argument_list|(
name|ServerContainer
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|)
argument_list|)
operator|.
name|map
argument_list|(
name|ServerContainer
operator|.
name|class
operator|::
name|cast
argument_list|)
operator|.
name|ifPresent
argument_list|(
name|container
lambda|->
name|JSR356WebSocketComponent
operator|.
name|registerServer
argument_list|(
name|contextPath
argument_list|,
name|container
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|contextDestroyed
parameter_list|(
specifier|final
name|ServletContextEvent
name|sce
parameter_list|)
block|{
name|JSR356WebSocketComponent
operator|.
name|unregisterServer
argument_list|(
name|sce
operator|.
name|getServletContext
argument_list|()
operator|.
name|getContextPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

