begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.camel.component.aws.ses
package|package
name|org
operator|.
name|apache
operator|.
name|camel
operator|.
name|component
operator|.
name|aws
operator|.
name|ses
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|com
operator|.
name|amazonaws
operator|.
name|services
operator|.
name|simpleemail
operator|.
name|AmazonSimpleEmailService
import|;
end_import

begin_comment
comment|/**  * The AWS SES component configuration properties  *   */
end_comment

begin_class
DECL|class|SesConfiguration
specifier|public
class|class
name|SesConfiguration
block|{
DECL|field|amazonSESClient
specifier|private
name|AmazonSimpleEmailService
name|amazonSESClient
decl_stmt|;
DECL|field|accessKey
specifier|private
name|String
name|accessKey
decl_stmt|;
DECL|field|secretKey
specifier|private
name|String
name|secretKey
decl_stmt|;
DECL|field|subject
specifier|private
name|String
name|subject
decl_stmt|;
DECL|field|from
specifier|private
name|String
name|from
decl_stmt|;
DECL|field|to
specifier|private
name|List
argument_list|<
name|String
argument_list|>
name|to
decl_stmt|;
DECL|field|returnPath
specifier|private
name|String
name|returnPath
decl_stmt|;
DECL|field|replyToAddresses
specifier|private
name|List
argument_list|<
name|String
argument_list|>
name|replyToAddresses
decl_stmt|;
DECL|method|getAccessKey ()
specifier|public
name|String
name|getAccessKey
parameter_list|()
block|{
return|return
name|accessKey
return|;
block|}
DECL|method|setAccessKey (String accessKey)
specifier|public
name|void
name|setAccessKey
parameter_list|(
name|String
name|accessKey
parameter_list|)
block|{
name|this
operator|.
name|accessKey
operator|=
name|accessKey
expr_stmt|;
block|}
DECL|method|getAmazonSESClient ()
specifier|public
name|AmazonSimpleEmailService
name|getAmazonSESClient
parameter_list|()
block|{
return|return
name|amazonSESClient
return|;
block|}
DECL|method|setAmazonSESClient (AmazonSimpleEmailService amazonSESClient)
specifier|public
name|void
name|setAmazonSESClient
parameter_list|(
name|AmazonSimpleEmailService
name|amazonSESClient
parameter_list|)
block|{
name|this
operator|.
name|amazonSESClient
operator|=
name|amazonSESClient
expr_stmt|;
block|}
DECL|method|getFrom ()
specifier|public
name|String
name|getFrom
parameter_list|()
block|{
return|return
name|from
return|;
block|}
DECL|method|setFrom (String from)
specifier|public
name|void
name|setFrom
parameter_list|(
name|String
name|from
parameter_list|)
block|{
name|this
operator|.
name|from
operator|=
name|from
expr_stmt|;
block|}
DECL|method|getTo ()
specifier|public
name|List
argument_list|<
name|String
argument_list|>
name|getTo
parameter_list|()
block|{
return|return
name|to
return|;
block|}
DECL|method|setTo (List<String> to)
specifier|public
name|void
name|setTo
parameter_list|(
name|List
argument_list|<
name|String
argument_list|>
name|to
parameter_list|)
block|{
name|this
operator|.
name|to
operator|=
name|to
expr_stmt|;
block|}
DECL|method|setTo (String to)
specifier|public
name|void
name|setTo
parameter_list|(
name|String
name|to
parameter_list|)
block|{
name|this
operator|.
name|to
operator|=
name|Arrays
operator|.
name|asList
argument_list|(
name|to
operator|.
name|split
argument_list|(
literal|","
argument_list|)
argument_list|)
expr_stmt|;
block|}
DECL|method|getSecretKey ()
specifier|public
name|String
name|getSecretKey
parameter_list|()
block|{
return|return
name|secretKey
return|;
block|}
DECL|method|setSecretKey (String secretKey)
specifier|public
name|void
name|setSecretKey
parameter_list|(
name|String
name|secretKey
parameter_list|)
block|{
name|this
operator|.
name|secretKey
operator|=
name|secretKey
expr_stmt|;
block|}
DECL|method|getSubject ()
specifier|public
name|String
name|getSubject
parameter_list|()
block|{
return|return
name|subject
return|;
block|}
DECL|method|setSubject (String subject)
specifier|public
name|void
name|setSubject
parameter_list|(
name|String
name|subject
parameter_list|)
block|{
name|this
operator|.
name|subject
operator|=
name|subject
expr_stmt|;
block|}
DECL|method|getReturnPath ()
specifier|public
name|String
name|getReturnPath
parameter_list|()
block|{
return|return
name|returnPath
return|;
block|}
DECL|method|setReturnPath (String returnPath)
specifier|public
name|void
name|setReturnPath
parameter_list|(
name|String
name|returnPath
parameter_list|)
block|{
name|this
operator|.
name|returnPath
operator|=
name|returnPath
expr_stmt|;
block|}
DECL|method|getReplyToAddresses ()
specifier|public
name|List
argument_list|<
name|String
argument_list|>
name|getReplyToAddresses
parameter_list|()
block|{
return|return
name|replyToAddresses
return|;
block|}
DECL|method|setReplyToAddresses (List<String> replyToAddresses)
specifier|public
name|void
name|setReplyToAddresses
parameter_list|(
name|List
argument_list|<
name|String
argument_list|>
name|replyToAddresses
parameter_list|)
block|{
name|this
operator|.
name|replyToAddresses
operator|=
name|replyToAddresses
expr_stmt|;
block|}
DECL|method|setReplyToAddresses (String replyToAddresses)
specifier|public
name|void
name|setReplyToAddresses
parameter_list|(
name|String
name|replyToAddresses
parameter_list|)
block|{
name|this
operator|.
name|replyToAddresses
operator|=
name|Arrays
operator|.
name|asList
argument_list|(
name|replyToAddresses
operator|.
name|split
argument_list|(
literal|","
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|toString ()
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"SesConfiguration{"
operator|+
literal|"accessKey='"
operator|+
name|accessKey
operator|+
literal|'\''
operator|+
literal|", amazonSESClient="
operator|+
name|amazonSESClient
operator|+
literal|", secretKey=xxxxxxxxxxxxxxx"
operator|+
literal|", subject='"
operator|+
name|subject
operator|+
literal|'\''
operator|+
literal|", from='"
operator|+
name|from
operator|+
literal|'\''
operator|+
literal|", to='"
operator|+
name|to
operator|+
literal|'\''
operator|+
literal|", returnPath='"
operator|+
name|returnPath
operator|+
literal|'\''
operator|+
literal|", replyToAddresses='"
operator|+
name|replyToAddresses
operator|+
literal|'\''
operator|+
literal|'}'
return|;
block|}
block|}
end_class

end_unit

